RedHatInsights/vulnerability-ui

src/Helpers/VulnerabilitiesHelper.js

dependent on https://github.com/RedHatInsights/insights-frontend-components/pull/267

fix(cve-table): use cvss parser from components

---

package-lock.json
package.json
src/Components/SmartComponents/CVEs/CVEs.js
src/Components/SmartComponents/CVEs/CVEs.scss

Depndent on https://github.com/RedHatInsights/insights-frontend-components/pull/290

feat(cve-table): rewrite table to PF4

---

src/Components/PresentationalComponents/CVEPageDetails/CVEPageDetails.js
src/Components/PresentationalComponents/ImpactBadge/ImpactBadge.js
src/Helpers/CVEHelper.js
src/Helpers/MiscHelper.js
src/Helpers/VulnerabilitiesHelper.js

Created a new PR with implemented feedback from Jiri Dostal. Old PR no. 15 closed without apply and split into separate ones per each JIRA task.

VMAAS-246 Impact badges as separated single component

---

src/Components/PresentationalComponents/CVEPageDetails/CVEPageDetails.js
src/Components/PresentationalComponents/CVEPageOverview/CVEPageOverview.js
src/Components/PresentationalComponents/CVERecordDescription/CVERecordDescription.js
src/Components/PresentationalComponents/CVERecordDescription/CVERecordDescription.scss
src/Components/SmartComponents/CVEs/CVEs.js
src/Helpers/MiscHelper.js
src/Helpers/VulnerabilitiesHelper.js

* Added tooltip for CVE Record Description
* Created custom component with CSS styles considering to different browser window sizes
* Fixed type &hellip;
* Fixed Publish Date title in all occurrences

VMAAS-289 CVE Record Description tooltip, Publish Date title format

---

src/Components/PresentationalComponents/CVEPageDetails/CVEPageDetails.js
src/Components/PresentationalComponents/CVEPageDetails/CVEPageDetails.scss
src/Components/PresentationalComponents/SeverityRating/SeverityRating.js
src/Components/PresentationalComponents/SeverityRating/SeverityRating.scss

VMAAS-169 CVE detail page header redesign according to new wireframe

---

src/Components/SmartComponents/Systems/Systems.js
src/Helpers/APIHelper.js
src/Store/Actions/Actions.js

This can be merged right now, but will not take any effect untill https://github.com/RedHatInsights/insights-frontend-components/pull/310 is merged.

Allow passing custom pagination to host inventory

---

src/Components/PresentationalComponents/WithLoader/WithLoader.js
src/Components/PresentationalComponents/WithLoader/WithLoader.test.js
src/Components/PresentationalComponents/WithLoader/__snapshots__/WithLoader.test.js.snap

WithLoader component - variant propType defined and unit tests added

---

src/Components/PresentationalComponents/CVEPageDetailsSeverity/__snapshots__/CVEPageDetailsSeverity.test.js.snap

CVEPageDetailsSeverity snapshot fixed

---

src/entry-dev.js
src/entry.js

Use dynamic basename for Router

---

src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js

Send PF table to exposed system table

---

package-lock.json
package.json
src/Components/SmartComponents/CVEs/VulnerabilitiesCves.js
src/Components/SmartComponents/Filters/Filters.js

Reflect parameters in the URL so we can link it externally.

feat(url-params): Propagate table parameters in the URL

---

src/Components/SmartComponents/BusinessRiskModal/BusinessRiskModal.js

fix(business-risk): remove justification helper text

---

src/Components/PresentationalComponents/Filters/FilterChips.js
src/Components/PresentationalComponents/Filters/Filters.js
src/Components/SmartComponents/CVEs/VulnerabilitiesCves.js
src/Components/SmartComponents/CVEs/VulnerabilitiesTableToolbar.js
src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
src/Components/SmartComponents/SystemCves/SystemCves.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js

Add filter chips

---

src/Components/SmartComponents/Systems/Systems.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js

fix(case): use sentence case in table headers

---

src/Components/PresentationalComponents/CVEPageDetailsDescription/CVEPageDetailsDescription.js
src/Components/PresentationalComponents/CVEPageDetailsDescription/__snapshots__/CVEPageDetailsDescription.test.js.snap

business risk justification should be displayed in popover

---

src/Components/SmartComponents/CVEs/vulnerabilities.scss

fix(style): drop publish date column while 100px wider

---

src/Components/PresentationalComponents/CVEPageDetails/__snapshots__/CVEPageDetails.test.js.snap
src/Components/PresentationalComponents/CVEPageDetailsDescription/CVEPageDetailsDescription.js
src/Components/PresentationalComponents/CVEPageDetailsDescription/CVEPageDetailsDescription.test.js
src/Components/PresentationalComponents/CVEPageDetailsDescription/SnippetWithHeaderAndTooltip.js
src/Components/PresentationalComponents/CVEPageDetailsDescription/__snapshots__/CVEPageDetailsDescription.test.js.snap
src/Components/PresentationalComponents/CVEPageDetailsDescription/__snapshots__/SnippetWithHeaderAndTooltip.test.js.snap
src/Components/PresentationalComponents/CvssVector/CvssVector.js
src/Components/PresentationalComponents/CvssVector/__snapshots__/CvssVector.test.js.snap

-  Spacing between "publish date" and "View in Red Hat CVE database" should be smaller. Use smaller spacer if possible. 
-  Business risk & status fields have incorrect label style. Use label class=“pf-c-form__label” https://www.patternfly.org/v4/documentation/core/components/form

Fix CVE Details design bugs

---

src/Components/PresentationalComponents/DownloadReportKebab/KebabItems.js
src/Components/SmartComponents/Systems/Systems.js
src/Helpers/constants.js

contains a small refactoring + UI enhancements and fixes

UI enhancements/bugs for systems

---

src/Components/SmartComponents/SystemCves/SystemCves.js

passing system ID fixes the issue

Fix download report in system detail page

---

src/Components/SmartComponents/CVEs/VulnerabilitiesTableToolbar.js

allow setting status only when a CVE is selected

---

src/Components/SmartComponents/CVEs/vulnerabilities.scss

Dependent on https://github.com/RedHatInsights/frontend-components/pull/207

fix(style): expansion arrow was not centered

---

src/Components/SmartComponents/CVEPage/CVEPage.js
src/Components/SmartComponents/CVEs/VulnerabilitiesTableToolbar.js
src/Components/SmartComponents/Modals/BaseModal.js
src/Components/SmartComponents/Modals/CvePairStatusModal.js
src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
src/Components/SmartComponents/SystemCves/SystemCves.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Helpers/CVEHelper.js

This PR it's all the overall CVE checkbox functionality. 
For the default state and when the checkbox should be checked will be in a seperate pr

Click overall CVE should apply the CVE's status

---

src/Components/SmartComponents/SystemCves/SystemCves.js

The PR fixes the following error:
and fix

fix(system-cves): Fix out of range error

---

src/Components/PresentationalComponents/CvssVector/CvssVector.js
src/Components/PresentationalComponents/SelectAllCheckbox.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js

Fixing the warning in the console about the prop-type checking

chore(prop-types): Fix prop-type warnings

---

src/Components/SmartComponents/CVEs/vulnerabilities.scss

Expansion arrow misalignment fixed

fix(CVEtable): Expansion arrow misalignment

---

src/Components/SmartComponents/CVEs/vulnerabilities.scss

Expansion arrow misalignment

---

config/spandx.config.js
package-lock.json
package.json
src/Components/PresentationalComponents/Filters/FilterChips.js
src/Components/SmartComponents/CVEs/VulnerabilitiesCves.js
src/Components/SmartComponents/CVEs/VulnerabilitiesTable.js
src/Components/SmartComponents/SystemCves/SystemCveTable.js
src/Components/SmartComponents/SystemCves/SystemCves.js

fixing eslint warning and errors

Update eslint plugin react

---

package-lock.json
package.json
src/Components/PresentationalComponents/Snippets/SnippetWithPopover.js
src/Helpers/VulnerabilitiesHelper.js

Status edit UI bug - Missing tooltip on status on a system view VMAAS-777

fix(SystemCvesTable): popover added to status column

---

src/Components/PresentationalComponents/Snippets/SnippetWithPopover.js
src/Helpers/CVEHelper.js
src/Helpers/CVEHelper.test.js

displaying status as title case 
before
after

Fix title case sentence

---

package-lock.json
package.json
src/Components/SmartComponents/CVEs/CVEs.js
src/Components/SmartComponents/CVEs/VulnerabilitiesCves.js
src/Components/SmartComponents/Reports/DownloadExecutive.js
src/Components/SmartComponents/Reports/ExecutiveReport.js
src/Components/SmartComponents/VulnerabilityHeader/VulnerabilityHeader.js
src/Helpers/APIHelper.js
src/Helpers/constants.js

[245f75ba-6be5-48db-9c17-4bc88d5ea8a5.pdf](https://github.com/RedHatInsights/vulnerability-ui/files/4071061/245f75ba-6be5-48db-9c17-4bc88d5ea8a5.pdf)
Due to the limitations of the library, I request the data as the component mounts. I will work on another PR to optimize it and request the data on click.

Add Executive report

---

src/Components/SmartComponents/Reports/ExecutiveReport.js

Fixing an inaccurate percentage. using what the backend provides me

fix(report): Fix percentages in the table

---

src/Components/SmartComponents/Reports/ExecutiveReport.js
src/Helpers/constants.js

verbal fixes
provide a better filename for the report

Report enhancements 

---

package-lock.json
package.json
src/Components/SmartComponents/Reports/ExecutiveReport.js

Update the package that has the fix for the canvas and update the language based on the latest changes

Report language

---

.travis/create_manifest.sh

Use the correct git repo to generate the manifest

fix(manifest): Fix generating package manifest

---

.travis.yml

chore(travis): Use stages in travis

---

src/Components/SmartComponents/Systems/Systems.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Store/Reducers/InventoryEntitiesReducer.js

fix(Systems): use inventory last seen column

---

src/Components/SmartComponents/Modals/BusinessRiskModal.js
src/Messages.js

title and info cause messed up
after

fix(Business risk modal): Fix translations keys

---

src/Components/SmartComponents/CVEs/VulnerabilitiesTableToolbar.js
src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js

chore(filtes): Change filtering order

---

locales/translations.json
src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.test.js
src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
src/Components/PresentationalComponents/CVEPageDetails/CVEPageDetails.js
src/Components/SmartComponents/CVEPage/CVEPage.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Helpers/VulnerabilitiesHelper.js
src/Messages.js

- generate rules by error keys

fix(csaw filters): Support dynamic filter

---

src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
src/Helpers/constants.js

Fixes [VMASS-1073](https://projects.engineering.redhat.com/browse/VMAAS-1073)

fix(csaw rules): Risk of change icon based on the value

---

src/Components/SmartComponents/SystemDetail/SystemDetail.js

Partially fixes: https://projects.engineering.redhat.com/browse/VMAAS-1075
Rest is API: https://projects.engineering.redhat.com/browse/VMAAS-1083

fix(system detail): Only show 1 empty state if invalid system id

---

src/Components/SmartComponents/CVEs/VulnerabilitiesTableToolbar.js

Fixes [VMASS-1008](https://projects.engineering.redhat.com/browse/VMAAS-1008)

fix(cve table toolbar): Fix overlap for small width screens

---

src/Components/PresentationalComponents/Snippets/TruncatedText.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Store/Actions/Actions.js

[Exposed system page with csaw rules](https://ci.foo.redhat.com:1337/rhel/vulnerability/cves/CVE-2018-12207)
**Before:**
11 errors
10 warnings
**After:**
8 errors
8 warnings
No change in functionality.

chore(debug): Reduced number of errors in dev console

---

src/Store/Actions/Actions.js

Fixes [VMASS-1083](https://projects.engineering.redhat.com/projects/VMAAS/issues/VMAAS-1083)

fix(empty state): Removed error notif when accessing deleted system

---

.travis.yml

https://docs.travis-ci.com/user/build-stages/#data-persistence-between-stages-and-jobs

fix(build):  travis jobs don't share storage

---

config/base.webpack.config.js
package-lock.json
package.json
src/index.js

The SVG will be loaded as data URL

fix(missing csaw icon): Load svg with url-loader

---

src/Components/PresentationalComponents/SelectAllCheckbox.js

Applies to all tables. Fixes [VMAAS-1146](https://projects.engineering.redhat.com/browse/VMAAS-1146).

fix(tables): Deselecting possible when all items filtered out

---

src/Components/SmartComponents/CVEs/VulnerabilitiesCves.js
src/Components/SmartComponents/Reports/DownloadExecutive.js
src/Components/SmartComponents/SystemCves/SystemCves.js
src/Components/SmartComponents/Systems/Systems.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js

Fixes [VMAAS-986](https://projects.engineering.redhat.com/browse/VMAAS-986).

fix(consistency): Consistent filenames of downloaded reports

---

src/Components/SmartComponents/CVEs/VulnerabilitiesCves.js
src/Components/SmartComponents/SystemCves/SystemCves.js
src/Components/SmartComponents/Systems/SystemsTableToolbar.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Helpers/DownloadReport.js

The functionality should remain the same

chore(download report): Unify functionality across the app

---

src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.test.js
src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleSummary.js
src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleSummary.test.js
src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleSummary.test.js.snap

chore(unit test): Cover csaw

---

src/Components/PresentationalComponents/CVEInfoBox/CVEInfoBox.scss
src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/ImpactFilter.js
src/Helpers/constants.js

Fixes: [VULN-943](https://projects.engineering.redhat.com/browse/VULN-943).

fix(cve toolbar): Added icons into impact filter dropdown

---

src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleSummary.js
src/Components/PresentationalComponents/CVETableExpandedCell/CVETableExpandedCell.js
src/Components/SmartComponents/Remediation/Remediation.js
src/Components/SmartComponents/SystemDetail/SystemDetail.js

chore(debug): Reduce number of errors in dev console

---

package-lock.json
package.json
src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/NotAffectingCVEsFilter.js
src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/SecurityRuleFilter.js
src/Helpers/TableToolbarHelper.js
src/Helpers/constants.js

Fixes:
1. security filter has no default selected option
2. selected option for "Show all CVEs" is missing after using some other filter
https://projects.engineering.redhat.com/browse/VULN-991
https://projects.engineering.redhat.com/browse/VULN-990

fix(vulnerabilities) primary-toolbar bug fixes

---

src/Components/PresentationalComponents/CVEPageDetailsDescription/CVEPageDetailsDescription.test.js
src/Components/PresentationalComponents/CVEPageDetailsDescription/__snapshots__/CVEPageDetailsDescription.test.js.snap

chore(test): Fixed snapshot test for CVEPageDetailsDesc

---

src/Components/SmartComponents/CVEs/VulnerabilitiesTableToolbar.js
src/Components/SmartComponents/Systems/Systems.js
src/Components/SmartComponents/Systems/SystemsTableToolbar.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Helpers/TableToolbarHelper.js

VULN-998:
Options in kebab menu in primary toolbar is clickable only on text, and the text is underlined
Options in kebab menu in table row are not underlined and the whole element is clickable
is fixed.

fix(Primary-KebabOptions) inconsistent kebab options fixed

---

src/Components/SmartComponents/Systems/Systems.js

Fixes [VULN-1013](https://projects.engineering.redhat.com/projects/VULN/issues/VULN-1013).

fix(notification): Show correct count of systems exluded

---

src/Components/SmartComponents/CVEs/VulnerabilitiesTableToolbar.js
src/Components/SmartComponents/Remediation/Remediation.js
src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js

fixes: [993](https://projects.engineering.redhat.com/browse/VULN-993
)
- removed the `Remediation` component from  `VulnerabilitiesTableToolbar.js` cause the showRemediationButton was never changed to true 
- fix the remediationProvider. Simplify the passing props and return the correct data to remetion

Fix(remediation):  Fix remediation provider

---

package-lock.json
package.json
src/Helpers/MiscHelper.js
src/Helpers/constants.js

@katerinapat this reduces the bundle size quite a lot!

Remove momentjs from dependencies, it was used for substractions only

---

src/Helpers/TableToolbarHelper.js

`buildActiveFilters` was quite hard to understand and messy, I wanted to make it more easy to understand. It is not really important change. Feel free to close if you think that it is not necessary

chore(FilterChips): buildActiveFilters function is refactored

---

src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js

promoting a fix for https://projects.engineering.redhat.com/browse/VULN-1047

Fix(select all): Call the function to return the params

---

src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/CvssBaseScoreFilter.test.js
src/Helpers/MiscHelper.js
src/Helpers/constants.js

Fixes: 
[VULN-923](https://projects.engineering.redhat.com/browse/VULN-923)

fix(CvssFilter) N/A cvss score filter option is added

---

src/Components/SmartComponents/SystemDetail/SystemDetail.js

file:///home/muslimjon/Videos/Peek%202020-06-04%2010-36.webm
I am not sure if this will solve, because I only faced this problem only twice during the whole day even if I downgraded my firefox to the version Patrik is using . So I would like to ask running it locally before merging. I suspected, [isOptOut](https://github.com/RedHatInsights/vulnerability-ui/blob/master/src/Components/SmartComponents/SystemDetail/SystemDetail.js#L38) is not set to undefined somehow

fix(SystemDetails) incorrect behaviour aftrer CTRL+SHIFT+R

---

src/Store/Reducers/CVEStore.test.js
src/Store/Reducers/InventoryEntitiesReducer.test.js
src/Store/Reducers/SystemCvesStore.test.js
src/Store/Reducers/SystemDetailStore.js
src/Store/Reducers/SystemDetailStore.test.js

[VULN-1026](https://projects.engineering.redhat.com/browse/VULN-1026)
I tried to work on testing :) Have a look and please tell everything that can be improved.

chore(Reducers): units tests for reducers

---

src/Components/SmartComponents/CVEs/VulnerabilitiesCves.js
src/Components/SmartComponents/SystemCves/SystemCves.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Helpers/MiscHelper.js

Fixes [VULN-1073](https://projects.engineering.redhat.com/browse/VULN-1073)

fix(CVE page): Incorrect URL params after editing status/BR

---

src/Components/SmartComponents/Modals/BaseModal.js

Part of [VULN-1067](https://projects.engineering.redhat.com/browse/VULN-1067).

fix(modals): Fix size after PF4 migration

---

src/Components/SmartComponents/SystemCves/SystemCves.js

https://marvelapp.com/75dcb1j/screen/58397735

fix(System detail page): Add bottom padding to table title

---

package-lock.json
package.json
src/App.js
src/Components/SmartComponents/InventoryDetail/InventoryDetail.js
src/Components/SmartComponents/Modals/BaseModal.js
src/Components/SmartComponents/Remediation/Remediation.js
src/Components/SmartComponents/Systems/Systems.js
src/Utilities/ReducerRegistry.js

fixes 
1. [1071](https://projects.engineering.redhat.com/browse/VULN-1071)
2. [1074](https://projects.engineering.redhat.com/browse/VULN-1074)

fix(notification): import notification package correctly

---

src/Components/SmartComponents/InsightsSystemRule/InsightsSystemRule.js
src/Components/SmartComponents/InsightsSystemRule/__snapshots__/InsightsSystemRule.test.js.snap

[Super picky UI review ](https://docs.google.com/document/d/1lUEUm6N4z6oEkBxE8Mg4YwuRbFXoOIX-zjG7aXl0uqQ) page 4.

Fix(Exposed systems page): Fixed expanded cell spacing

---

src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js

This change doesn't actually solve the issue but the re-build of the code.

fix(systems exposed toolbar):  Re run the build

---

src/Components/SmartComponents/SystemCves/SystemCves.js

urlParams was not being applied on load in System Details page.
Before:
after:

fix(SystemDetails) urlParams was not being applied on load

---

src/Helpers/VulnerabilitiesHelper.js
src/Helpers/VulnerabilitiesHelper.test.js

Fixes [VULN-1110](https://projects.engineering.redhat.com/projects/VULN/issues/VULN-1110).

fix(layout): CSAw icon aligned with text

---

src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/NotAffectingCVEsFilter.js
src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/NotAffectingCvesFilter.test.js
src/Components/SmartComponents/CVEs/VulnerabilitiesCves.js
src/Components/SmartComponents/CVEs/VulnerabilitiesTable.js
src/Components/SmartComponents/CVEs/VulnerabilitiesTableToolbar.js
src/Helpers/VulnerabilitiesHelper.js
src/Helpers/VulnerabilitiesHelper.test.js
src/Store/Reducers/VulnerabilitiesStore.js
src/Store/Reducers/VulnerabilitiesStore.test.js

Resolves: [VULN-1091](https://projects.engineering.redhat.com/browse/VULN-1091)
There are a few changes:
1. Hide and Show values in NotAffectingFilters were opposite in meaning, resulting in extra code e.g. `const params = { ...parameters, show_all: !parameters.show_all };` in cves page. it is fixed.
2. Apparently,` table.current `causes `urlParameters` to be ignored on load in CVEs and System details page. Thus, isFirstLoad is again used in this PR ::)

chore(CVEsPage) cves page is refactored to functional component

---

src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleSummary.js

Partially fixes [VULN-1119](https://projects.engineering.redhat.com/browse/VULN-1119).

fix(layout): Fixed CSAw rule summary spacing

---

src/Components/SmartComponents/Modals/CvePairStatusModal.js
src/Components/SmartComponents/Modals/CveStatusModal.js

From [Super picky UI review](https://docs.google.com/document/d/1lUEUm6N4z6oEkBxE8Mg4YwuRbFXoOIX-zjG7aXl0uqQ/) comments on page 6/7.

fix(modals): Tooltips triggered by click, not only hover

---

src/Components/SmartComponents/Modals/CvePairStatusModal.js
src/Components/SmartComponents/SystemCves/SystemCveTable.js
src/Components/SmartComponents/SystemCves/SystemCves.js
src/Components/SmartComponents/SystemDetail/SystemDetail.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Helpers/CVEHelper.js
src/Helpers/CVEHelper.test.js

Additionally fixes [VULN-901](https://projects.engineering.redhat.com/browse/VULN-901), see comment on JIRA.

fix(pair status modal): Show system display name not id

---

package-lock.json
package.json
src/Components/SmartComponents/CVEs/CVEs.test.js
src/Components/SmartComponents/CVEs/CVEsTable.js
src/Components/SmartComponents/CVEs/CVEsTable.test.js
src/Components/SmartComponents/CVEs/CVEsTableToolbar.test.js
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTableToolbar.test.js.snap
src/Components/SmartComponents/LandingPage/LandingPage.test.js
src/Components/SmartComponents/LandingPage/__snapshots__/LandingPage.test.js.snap

Unit test cves page

---

src/Components/SmartComponents/SystemCves/SystemCveTable.js
src/Helpers/selectAllCheckboxHelper.js

fix(detail): do not access data if no CVEs found

---

src/Components/SmartComponents/CVEs/CVEsTable.js
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap
src/Components/SmartComponents/SystemCves/SystemCveTable.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Helpers/CVEHelper.js
src/Helpers/CVEHelper.test.js

Fixes [VULN-1092](https://projects.engineering.redhat.com/projects/VULN/issues/VULN-1092).

fix(tables): Removed redundant kebab on expanded rows

---

src/Components/SmartComponents/Modals/BaseModal.js

Fixes: https://projects.engineering.redhat.com/browse/VULN-934

fix(Notifications): notifications are cleared on unmount

---

src/Components/SmartComponents/CVEs/CVEsTable.js
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap
src/Components/SmartComponents/SystemCves/SystemCveTable.js

Fixes [VULN-1133](https://projects.engineering.redhat.com/browse/VULN-1133).

fix(CVEs tables): Removed redundant expand button in expanded cell

---

package-lock.json
package.json

fix(primary toolbar): Update version

---

src/Components/SmartComponents/SystemDetailsPage/SystemDetails.test.js
src/Components/SmartComponents/SystemDetailsPage/SystemDetailsPage.js
src/Components/SmartComponents/SystemDetailsPage/SystemDetailsPage.test.js
src/Components/SmartComponents/SystemDetailsPage/__snapshots__/SystemDetails.test.js.snap
src/Components/SmartComponents/SystemDetailsPage/__snapshots__/SystemDetailsPage.test.js.snap

Some changes in SystemDetailsPage: 
1. linkHovered: false deleted 
2. checkItem and toggleLinkHover functions are deleted as they were not used anywhere

chore(SystemDetails) unit test for SystemDetails, SystemDetailsPage

---

src/Components/SmartComponents/Reports/BuildExecReport.js

Fixes [VULN-1144](https://projects.engineering.redhat.com/browse/VULN-1144).

fix(exec. report): Fix CVSS breakdown table when CVE count was 0

---

package-lock.json
package.json
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap
src/Components/SmartComponents/SystemDetailsPage/__snapshots__/SystemDetails.test.js.snap

fix(headers): headers misalignment fix by updating pf-table

---

src/Components/SmartComponents/Reports/Common/firstPagePDF.js
src/Components/SmartComponents/Reports/DownloadCVEsReport.js

fixes https://projects.engineering.redhat.com/browse/VULN-1197

fix(reports): Add author name for custom reports

---

src/Components/SmartComponents/Reports/DownloadCVEsReport.js

Fixes [VULN-1204](https://projects.engineering.redhat.com/projects/VULN/issues/VULN-1204).

fix(PDF report): Apply table sort option

---

src/Components/SmartComponents/Reports/DownloadCVEsReport.js
src/Helpers/DownloadReport.js

changing the name to differentiate it from the executive report

fix(pdf report):  Change filename

---

locales/data.json
locales/translations.json
src/Components/SmartComponents/Modals/ReportConfigModal.js
src/Helpers/constants.js
src/Messages.js

Fixes [VULN-1209](https://projects.engineering.redhat.com/projects/VULN/issues/VULN-1209).

fix(config modal): Rename systems exposed checkbox label

---

config/base.webpack.config.js
package-lock.json
package.json
src/Components/SmartComponents/InsightsSystemRule/__snapshots__/InsightsSystemRule.test.js.snap

Bump remediation to 2.1.4 and update couple of other dependencies

Bump remediation to 2.1.4

---

src/Components/SmartComponents/Reports/Common/tablePage.js
src/Components/SmartComponents/Reports/DownloadCVEsReport.js

Fixes [VULN-1207](https://projects.engineering.redhat.com/browse/VULN-1207).

fix(PDF report): Fallback to CVSS v2 if v3 not present

---

src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Components/SmartComponents/SystemsExposedTable/__snapshots__/SystemsExposedTable.test.js.snap

finally fixes https://projects.engineering.redhat.com/browse/VULN-1155

fix(remediation): Add RemediationButton as dedicatedAction

---

src/Components/SmartComponents/Modals/ReportConfigModal.js

Fixes [VULN-1210](https://projects.engineering.redhat.com/projects/VULN/issues/VULN-1210).
Manual state reset, another solution might be to remount the component.

fix(config modal): Reset data on modal close

---

src/Components/SmartComponents/SystemCves/SystemCves.js
src/Components/SmartComponents/SystemDetailsPage/SystemDetails.js

Maybe fixes [VULN-1173](https://projects.engineering.redhat.com/projects/VULN/issues/VULN-1173).

fix(system detail): Add ability to hide table title label

---

src/Components/SmartComponents/Reports/DownloadCVEsReport.js

Has to be commited after: https://github.com/RedHatInsights/frontend-components/pull/703
Fixes [VULN-1214](https://projects.engineering.redhat.com/projects/VULN/issues/VULN-1214).
First page is prone to overflow, addressed in [VULN-1231](https://projects.engineering.redhat.com/projects/VULN/issues/VULN-1231).

fix(PDF reports): Change page orientation to landscape

---

src/App.js

I noticed that Vulnerability has also this [SPM-409](https://projects.engineering.redhat.com/browse/SPM-409). Feel free to improve the PR ::)

fix(ChromeNav): fix navigation on page change

---

src/Components/SmartComponents/CVEs/CVEsTable.js
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap
src/Components/SmartComponents/SystemCves/SystemCveTable.js
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Components/SmartComponents/SystemsExposedTable/__snapshots__/SystemsExposedTable.test.js.snap
src/Components/SmartComponents/SystemsPage/SystemsPage.js

feat(sticky header): Introduce sticky headers for all the tabls

---

package-lock.json
package.json
src/Components/SmartComponents/Reports/Common/tablePage.js

fixes: https://projects.engineering.redhat.com/browse/VULN-1217

fix(pdf reports): Add CSAw icon to indicate security rule

---

src/Components/SmartComponents/Reports/Common/tablePage.js

chore(pdf reports): Re-order Csaw icon

---

package-lock.json
package.json
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap

Fixes [VULN-1240](https://projects.engineering.redhat.com/projects/VULN/issues/VULN-1240).

[hotfix/qa-stable] Fix table headers not having correct height

---

package-lock.json
package.json
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap

Fixes [VULN-1240](https://projects.engineering.redhat.com/projects/VULN/issues/VULN-1240).

[hotfix/ci-stable] Fix table headers not having correct height

---

package-lock.json
package.json
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap

Fixes [VULN-1240](https://projects.engineering.redhat.com/projects/VULN/issues/VULN-1240).

[hotfix/prod-stable] Fix table headers not having correct height

---

src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.test.js
src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
src/Components/PresentationalComponents/CVEPageDetails/CVEPageDetails.js
src/Components/PresentationalComponents/CVEPageDetails/CVEPageDetails.test.js
src/Components/PresentationalComponents/CVEPageDetails/__snapshots__/CVEPageDetails.test.js.snap
src/Components/SmartComponents/InsightsSystemRule/InsightsSystemRule.test.js
src/Components/SmartComponents/InsightsSystemRule/__snapshots__/InsightsSystemRule.test.js.snap
src/Helpers/CVEHelper.js
src/Helpers/CVEHelper.test.js
src/Store/Actions/Actions.js

fix: https://projects.engineering.redhat.com/browse/VULN-1180

1180 filters cve dp

---

locales/data.json
locales/translations.json
src/Components/SmartComponents/Reports/Common/tablePage.js
src/Components/SmartComponents/SystemsPage/SystemsPage.js
src/Messages.js

Fixes [VULN-1250](https://projects.engineering.redhat.com/browse/VULN-1250).
Also adds ability to localize "Excluded" inside Systems table

fix(PDF report): Show excluded for CVE count of excluded systems

---

src/Components/PresentationalComponents/CSAwIcon/CSAwIcon.js
src/Components/SmartComponents/SystemCves/SystemCveTable.js
src/Helpers/VulnerabilityHelper.js

Fixes [VULN-1159](https://projects.engineering.redhat.com/browse/VULN-1159).

fix(systems exposed table): Fix system name alignment

---

src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js

fixes https://issues.redhat.com/browse/VULN-1271

fix(systems exposed): Hide edit actions on empty page

---

src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
src/Components/PresentationalComponents/CVEPageDetailsDescription/CVEPageDetailsDescription.js
src/Components/PresentationalComponents/CVEPageDetailsDescription/__snapshots__/CVEPageDetailsDescription.test.js.snap
src/Components/SmartComponents/InsightsSystemRule/InsightsSystemRule.js
src/Components/SmartComponents/Modals/CvePairStatusModal.test.js
src/Components/SmartComponents/Modals/CveStatusModal.test.js
src/Components/SmartComponents/SystemDetailsPage/SystemDetails.test.js
src/Helpers/DownloadReport.js
src/Helpers/DownloadReport.test.js

Addresses [VULN-1253](https://issues.redhat.com/browse/VULN-1253).
Output lines before: 1238
Output lines after: 650
Reduction by 48%
Resolved warnings like:
- wrap state updates into act(() => {...})
- div cannot be descendant of p (CSAwRulebox)
- using patternfly theme provider included deprecated componentWillMount and componentWillReceiveProps (CVE details desc)
- accessing property of undefined (Download report)
- using isRequired for optional props (Insights systems rule; component can handle absent prop by displaying InsightsNoSystemRule)
- other prop types errors

chore(tests): Fix some console warnings

---

src/App.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Components/SmartComponents/SystemsExposedTable/__snapshots__/SystemsExposedTable.test.js.snap
src/Components/SmartComponents/SystemsPage/SystemsPage.js
src/Store/Reducers/InventoryEntitiesReducer.js
src/Store/Reducers/InventoryEntitiesReducer.test.js

Display tags column in 
1. systems paga
2. CVE details page for system exposed table

feat(systems table): Display tags column

---

src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap
src/Helpers/constants.js
src/Store/Reducers/InventoryEntitiesReducer.js
src/Store/Reducers/InventoryEntitiesReducer.test.js

fix the ugly truncated columns

fix(table columns): Don't truncate column headers

---

src/App.scss
src/Components/SmartComponents/Modals/ReportConfigModal.js
src/Components/SmartComponents/Reports/CustomReportFilter.js

Resolves [VULN-1284](https://issues.redhat.com/browse/VULN-1284).

feat(report config modal): New filter options

---

src/Components/SmartComponents/SystemCves/SystemCves.js
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
src/Components/SmartComponents/SystemDetailsPage/SystemDetails.js
src/Components/SmartComponents/SystemDetailsPage/__snapshots__/SystemDetails.test.js.snap

Addresses [VULN-1303](https://issues.redhat.com/browse/VULN-1303), vuln package in inventory necessary after merging.
Title is not set for system detail page from inventory view.

fix(system detail page): Don't change page title by default

---

src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap
src/Components/SmartComponents/SystemDetailsPage/__snapshots__/SystemDetails.test.js.snap
src/Helpers/constants.js

VULN-1207 Fix(columns): Nowrap for columns with icon

---

src/Helpers/constants.js
src/Store/Reducers/CVEDetailsPageStore.js

Fixes [VULN-1311](https://issues.redhat.com/browse/VULN-1311).

fix(system tables): Fix "last seen" column sort

---

src/Components/SmartComponents/Reports/BuildExecReport.js

Fixes [VULN-1330](https://issues.redhat.com/projects/VULN/issues/VULN-1330).
Not the prettiest solution, but I guess this component will be improved when we implement new exec report features after the release.

fix(executive report): Fix incorrect percentage in pie chart

---

src/Components/PresentationalComponents/CvssVector/CvssVector.js

Fixes [VULN-1326](https://issues.redhat.com/projects/VULN/issues/VULN-1326).

Fix(vulnerability header): Fix CVSS vector label spacing

---

src/Components/SmartComponents/Modals/ReportConfigModal.test.js
src/Components/SmartComponents/Modals/__snapshots__/ReportConfigModal.test.js.snap

Coverage is not 100% only 80%, I wasn't able to test textboxes, probably because of [this enzyme bug](https://github.com/enzymejs/enzyme/issues/2316).

chore(tests): Unit tests for ReportConfigModal

---

src/Components/SmartComponents/Reports/Common/tablePage.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Components/SmartComponents/SystemsPage/SystemsPage.js
src/Helpers/constants.js
src/Store/Reducers/CVEDetailsPageStore.js
src/Store/Reducers/SystemsPageStore.js
src/Store/Reducers/SystemsPageStore.test.js

Fixes [VULN-1329](https://issues.redhat.com/projects/VULN/issues/VULN-1329), [VULN-1311](https://issues.redhat.com/browse/VULN-1311) and [VULN-1249](https://issues.redhat.com/projects/VULN/issues/VULN-1249).
- sort by 'updated' not 'last_upload' by default on both systems tables
- when sorting by 'last seen' column use 'updated' not 'last_upload' on both systems tables
- fixes sorting not applying on correct column systems exposed page.
- fixes current sorting column indication sometimes not showing
Also I noticed Export by PDF on Systems page doesn't include tags column, not sure if this is intended.

fix(systems tables): Enhance sorting

---

src/App.scss
src/Components/SmartComponents/Reports/ReportsPage.js
src/Components/SmartComponents/Reports/__snapshots__/ReportsPage.test.js.snap

Fixes [VULN-1338](https://issues.redhat.com/projects/VULN/issues/VULN-1338).

fix(reports page): Improve layout

---

src/Components/PresentationalComponents/BasePfComponents/BaseDropdown.js
src/Components/SmartComponents/CVEDetailsPage/CVEDetailsPage.js
src/Components/SmartComponents/CVEDetailsPage/CveDetailsPage.test.js
src/Messages.js

replace kebab
with dropdown 
* spacing and style it might change

VULN-1345 fix(kebab): Replace kebab action with dropdown

---

.dependabot/config.yml

enable weekly dependabot checks

chore(config): Enable dependabot

---

src/Components/PresentationalComponents/AdvisoryColumn/AdvisoryColumn.js
src/Components/PresentationalComponents/CVEPageDetails/CVEPageDetails.js
src/Components/PresentationalComponents/CVEPageDetails/__snapshots__/CVEPageDetails.test.js.snap
src/Components/PresentationalComponents/Header/Header.js
src/Components/SmartComponents/Reports/__snapshots__/ReportsPage.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap
src/Components/SmartComponents/SystemDetailsPage/__snapshots__/SystemDetailsPage.test.js.snap

Fixes [VULN-1385](https://issues.redhat.com/browse/VULN-1385).

fix: Fix various UI layout bugs

---

src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.scss
src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
src/Helpers/constants.js

Display severity using InsightsLabel and rearrange csaw rule information according to the mock up

VULN-1383 feat(csaw rule card): Display rule's severity value

---

src/Components/SmartComponents/SystemDetailsPage/__snapshots__/SystemDetails.test.js.snap
src/Store/Reducers/CVEDetailsPageStore.js
src/Store/Reducers/SystemCvesStore.js
src/Store/Reducers/SystemCvesStore.test.js

This reverts commit c934220414d5209bd7d3d9dde4e1c55df1cf517e.

Revert "HOTFIX: Disable advisory column"

---

locales/en.json
src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
src/Messages.js

VULN-1416 feat(csaw rule): Display number of affected system

---

src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/AffectingFilter.js
src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/ExcludedFilter.js

[VULN-1413](https://issues.redhat.com/browse/VULN-1413)

VULN-1413 fix: Excluded and affecting filters reset page to 1

---

.travis/custom_release.sh

The only change I introduce with this PR would be for master branch. 
Whenever master has an update it will trigger a release for 
1. ci-beta
2. qa-beta
The rest should remain that same

chore(custom release): Add custom release script

---

src/Components/PresentationalComponents/ErrorHandler/ErrorHandler.js
src/Components/SmartComponents/SystemsPage/SystemsPage.js
src/Store/Reducers/SystemsPageStore.js
src/Store/Reducers/SystemsPageStore.test.js
src/Store/Reducers/reducersContansts.js

fix(systems page): Handle error on systems page

---

src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.test.js

Fixes [VULN-1449](https://issues.redhat.com/projects/VULN/issues/VULN-1449).

fix(CSAw box): Remove rule presence false filter when filtering by rule

---

package-lock.json
package.json

**Fixes [VULN-1497](https://issues.redhat.com/browse/VULN-1497).**
**This bug is present in production.**

VULN-1497 fix(exec report): Fix missing pie chart

---

package-lock.json
package.json
src/Utilities/Routes.js

Removes changes to the chrome root element. This element is destroyed when a chrome 2 application is rendered. Trying to change it can cause runtime crashes.
cc @katerinapat

Remove chrome root element mutation

---

.github/dependabot.yml

open PRs weekly and not daily. Monday is the day :)

chore(Dependabot): Change interval from daily to weekly

---

src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.scss
src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
src/Components/PresentationalComponents/CVEDetailsPageSidebar/CVEDetailsPageSidebar.js
src/Components/PresentationalComponents/CVEDetailsPageSidebar/__snapshots__/CVEDetailsPageSidebar.test.js.snap
src/Components/PresentationalComponents/CVEDetailsPageSummary/__snapshots__/CVEDetailsPageSummary.test.js.snap
src/Components/SmartComponents/CVEDetailsPage/CVEDetailsPage.js
src/Helpers/MiscHelper.js
src/Helpers/MiscHelper.test.js
src/Helpers/constants.js

- remove shadow from CSAw rulebox
- severity label should be bold and have appropriate color
- fix invalid 'labels' prop-type error in console

fix(CVE header): Fix minor bugs with new CVE header restyle

---

src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
src/Components/SmartComponents/Reports/DownloadCVEsReport.js
src/Components/SmartComponents/Reports/DownloadExecutive.js
src/Components/SmartComponents/Reports/DownloadSystemsReport.js
src/Components/SmartComponents/Reports/ReportsPage.js
src/Components/SmartComponents/SystemsPage/SystemsTableToolbar.js
src/Helpers/Hooks.js
src/Helpers/MiscHelper.js
src/Helpers/constants.js

Having a file that is responsible for more than one thing can lead to issues like this one 
https://issues.redhat.com/browse/VULN-1578 . So I split them into two 
I'll refactor `tablePage` and `firstPagePDF` in different PR. Both need to be more dump and abstract

VULN-1578 Refactor reports

---

src/Components/SmartComponents/CVEs/CVEs.js
src/Components/SmartComponents/CVEs/CVEs.test.js
src/Components/SmartComponents/CVEs/CVEsTable.js
src/Components/SmartComponents/CVEs/CVEsTable.test.js
src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
src/Components/SmartComponents/CVEs/CVEsTableToolbar.test.js
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTableToolbar.test.js.snap
src/Components/SmartComponents/SystemCves/SystemCveTable.js
src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
src/Components/SmartComponents/SystemCves/SystemCves.js
src/Components/SmartComponents/SystemCves/SystemCves.test.js
src/Components/SmartComponents/SystemCves/SystemCvesTable.test.js
src/Components/SmartComponents/SystemCves/SystemCvesTableToolbar.test.js
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTableToolbar.test.js.snap
src/Components/SmartComponents/SystemDetailsPage/__snapshots__/SystemDetails.test.js.snap
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.test.js
src/Helpers/CVEHelper.js
src/Helpers/CVEHelper.test.js
src/Store/Reducers/CVEDetailsPageStore.js
src/Store/Reducers/CVEDetailsPageStore.test.js
src/Store/Reducers/CVEsStore.js
src/Store/Reducers/CVEsStore.test.js
src/Store/Reducers/SystemCvesStore.js
src/Store/Reducers/SystemCvesStore.test.js

As part of  unifying the selectors. I started with the selector connected to the expand functionality  
1. expandedRows
2.  isAllExpanded

VULN-1246 chore(selectors): Unify selector for expanded rows

---

src/Components/SmartComponents/Reports/DownloadCVEsReport.js
src/Components/SmartComponents/Reports/DownloadExecutive.js
src/Components/SmartComponents/Reports/DownloadSystemsReport.js
src/Components/SmartComponents/SystemsPage/SystemsPage.js
src/Helpers/Hooks.js

- url param opt_out doesn't exist
- use the custom hook for notification on systems pages
modify `useNotifaction` hooks. make it more dump in order to accept the translated messages, it should not be responsible for  that

VULN-1585 fix(systems page): Fix notification when you opt out/in a system

---

src/Components/SmartComponents/Reports/Executive/ThirdPage.js

VULN-1589 fix(executive report): Display correct severity of the rule

---

src/Components/SmartComponents/Reports/Executive/ThirdPage.js
src/Helpers/VulnerabilityHelper.js

VULN-1558 fix(executive report): Add  line break for associated cves

---

.eslintrc.yml
src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
src/Components/PresentationalComponents/CVEDetailsPageDescription/CVEDetailsPageDescription.js
src/Components/PresentationalComponents/CVEDetailsPageSidebar/CVEDetailsPageSidebar.js
src/Components/PresentationalComponents/CVETableExpandedCell/CVETableExpandedCell.js
src/Components/PresentationalComponents/CvssVector/CvssVector.js
src/Components/PresentationalComponents/Filters/CustomFilters/CheckboxCustomFilter.js
src/Components/PresentationalComponents/Filters/CustomFilters/CvssCustomFilter.js
src/Components/PresentationalComponents/Snippets/CSAwLabel.js
src/Components/PresentationalComponents/Snippets/SnippetWithPopover.js
src/Components/SmartComponents/Modals/BaseModal.js
src/Components/SmartComponents/Modals/BusinessRiskModal.js
src/Components/SmartComponents/Modals/ReportConfigModal.js
src/Components/SmartComponents/Remediation/Remediation.js
src/Components/SmartComponents/Reports/CustomReportFilter.js
src/Components/SmartComponents/SystemDetailsPage/SystemDetailsPage.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js

https://eslint.org/docs/rules/jsx-quotes

chore: Add JSX attributes double quotes eslint rule

---

package-lock.json
package.json
src/Components/SmartComponents/Remediation/Remediation.js
src/Components/SmartComponents/Reports/Common/styles.js
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap

This also improves bundle size by about 3%.

VULN-1563 chore: Remove deprecated @patternfly/react-styled-system package

---

package-lock.json
package.json
src/Components/PresentationalComponents/CVEDetailsPageSidebar/__snapshots__/CVEDetailsPageSidebar.test.js.snap
src/Components/PresentationalComponents/CVEDetailsPageSummary/__snapshots__/CVEDetailsPageSummary.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTableToolbar.test.js.snap
src/Components/SmartComponents/SystemDetailsPage/__snapshots__/SystemDetails.test.js.snap
src/Components/SmartComponents/SystemDetailsPage/__snapshots__/SystemDetailsPage.test.js.snap
src/Components/SmartComponents/SystemsExposedTable/__snapshots__/SystemsExposedTable.test.js.snap

- compact skeleton table
- fix console spam "boundary prop deprecated"
- unblock new reset filter behaviour

chore(deps): Update FEC to 3.1.7

---

src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/KnownExploitFilter.js

fixes the issue 
https://user-images.githubusercontent.com/3369346/114007473-ac9aae00-9861-11eb-812f-da759d4a9092.mov

fix(exploit filter): Pass correct type of known exploit values

---

locales/en.json
src/Components/SmartComponents/Reports/Common/CVElabels.js
src/Components/SmartComponents/Reports/Common/FooterPDF.js
src/Components/SmartComponents/Reports/Common/firstPagePDF.js
src/Components/SmartComponents/Reports/Common/styles.js
src/Components/SmartComponents/Reports/Common/tablePage.js
src/Components/SmartComponents/Reports/DownloadCVEsReport.js
src/Components/SmartComponents/Reports/DownloadExecutive.js
src/Components/SmartComponents/Reports/Executive/SecondPage.js
src/Components/SmartComponents/Reports/ReportsHelper.js
src/Helpers/constants.js
src/Messages.js

- some clean up and refactoring
display labels in PDF

VULN-1608 feat(pdf): Display exploit label in PDF

---

src/App.scss
src/Components/SmartComponents/SystemsPage/SystemsTableToolbar.js

VULN-1475 chore(toolbar): Update toolbar spacing to 16px

---

src/Store/Actions/Actions.js
src/Store/Reducers/CVEsStore.js
src/Store/Reducers/CVEsStore.test.js
src/Store/Reducers/SystemsPageStore.js
src/Store/Reducers/SystemsPageStore.test.js
src/Store/Reducers/reducersHelper.js

fixes: https://issues.redhat.com/browse/VULN-1419

VULN-1419 fix(systems page): Fix race condition when applying filters

---

src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTableToolbar.test.js.snap
src/Components/SmartComponents/Modals/ReportConfigModal.js
src/Components/SmartComponents/Modals/__snapshots__/ReportConfigModal.test.js.snap
src/Components/SmartComponents/Reports/__snapshots__/ReportsPage.test.js.snap
src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTableToolbar.test.js.snap
src/Components/SmartComponents/SystemDetailsPage/__snapshots__/SystemDetails.test.js.snap
src/Helpers/constants.js

chore(filters): Reorder filters according to mockups

---

src/App.scss

VULN-1623 chore: Auto width for dropdown filter text

---

src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.scss
src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.test.js
src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
src/Components/PresentationalComponents/KnownExploitSummary/KnownExploitSummary.js
src/Components/PresentationalComponents/KnownExploitSummary/__snapshots__/KnownExploitSummary.test.js.snap

Resolves [VULN-1631](https://issues.redhat.com/browse/VULN-1631).
Restyle according to these mockups: https://marvelapp.com/prototype/617efd0/screen/77966073

feat(CVE detail page): Expandable security rule and known exploit info

---

src/Components/PresentationalComponents/Snippets/GroupedCVELabels.js
src/Components/SmartComponents/CVEs/CVEs.test.js
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap
src/Components/SmartComponents/SystemCves/SystemCves.test.js
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap

fix: Fix compact table rows height

---

src/App.scss

Fixes [VULN-1552](https://issues.redhat.com/projects/VULN/issues/VULN-1552).

VULN-1552 fix: Align pagination correctly in system table toolbars

---

package.json

chore: Prevent tests from printing messages through the console

---

package-lock.json
package.json
src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.scss
src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
src/Components/PresentationalComponents/KnownExploitSummary/__snapshots__/KnownExploitSummary.test.js.snap
src/Components/SmartComponents/InsightsSystemRule/InsightsSystemRule.js
src/Components/SmartComponents/Modals/__snapshots__/ReportConfigModal.test.js.snap

fix: Rule card css tweaks

---

package-lock.json
package.json
src/Components/SmartComponents/Remediation/Remediation.js

This reverts commit 628d0948297ccc92c5119f1a86b1f16a5f834dce.

Revert "hotfix: Revert remediation"

---

src/Components/PresentationalComponents/AdvisoryColumn/AdvisoryColumn.js
src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleSummary.js
src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleSummary.test.js.snap
src/Components/PresentationalComponents/CVEDetailsPageDescription/SnippetWithHeaderAndPopover.js
src/Components/PresentationalComponents/CVEDetailsPageDescription/__snapshots__/SnippetWithHeaderAndPopover.test.js.snap
src/Components/PresentationalComponents/CVEDetailsPageSidebar/__snapshots__/CVEDetailsPageSidebar.test.js.snap
src/Components/PresentationalComponents/CVEDetailsPageSummary/__snapshots__/CVEDetailsPageSummary.test.js.snap
src/Components/PresentationalComponents/CVETableExpandedCell/CVETableExpandedCell.js
src/Components/PresentationalComponents/Snippets/Label.js
src/Components/PresentationalComponents/Snippets/SnippetWithPopover.js
src/Components/PresentationalComponents/Snippets/__snapshots__/SnippetWithPopover.test.js.snap
src/Components/PresentationalComponents/StatusColumn/StatusColumn.js
src/Components/SmartComponents/InsightsSystemRule/__snapshots__/InsightsSystemRule.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap

Fixes [VULN-1653](https://issues.redhat.com/browse/VULN-1653).
1. Add spacer to icon
2. Underline and set color to white
3. Add spacer between rule name and desc
4. Fix missing stylesheet

VULN-1653 fix: Various table issues

---

src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
src/Components/SmartComponents/CVEs/CVEsTableToolbar.test.js
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTableToolbar.test.js.snap
src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
src/Components/SmartComponents/SystemCves/SystemCvesTableToolbar.test.js
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTableToolbar.test.js.snap
src/Components/SmartComponents/SystemDetailsPage/__snapshots__/SystemDetails.test.js.snap

VULN-1551 feat: Patternfly expand all

---

src/Components/SmartComponents/InsightsSystemRule/__snapshots__/InsightsSystemRule.test.js.snap
src/Helpers/VulnerabilityHelper.js
src/Helpers/VulnerabilityHelper.test.js
src/Helpers/constants.js
src/Helpers/constants.test.js

fix(exposed system table): Remove security rule label

---

src/Components/SmartComponents/Modals/ReportConfigModal.js
src/Components/SmartComponents/Modals/__snapshots__/ReportConfigModal.test.js.snap
src/Components/SmartComponents/Reports/__snapshots__/ReportsPage.test.js.snap

VULN-1647 chore: Append modal in root element

---

src/App.scss

VULN-1653 fix: Advisory not available link color

---

src/Store/Reducers/InventoryEntitiesReducer.js

Fixes [VULN-1662](https://issues.redhat.com/browse/VULN-1662).

VULN-1662 fix: Fix last seen column wrap

---

locales/en.json
src/Components/SmartComponents/Reports/Common/__snapshots__/firstPagePDF.test.js.snap
src/Messages.js

chore: Fix error with missing error clause

---

src/Components/SmartComponents/CVEDetailsPage/CVEDetailsPage.js
src/Components/SmartComponents/Modals/BaseModal.js
src/Components/SmartComponents/Modals/BusinessRiskModal.js
src/Components/SmartComponents/SystemCves/SystemCves.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js

Tried to safely add the missing dependencies. There are still 2 places where I need to think more how to solve it .
Regarding the dispatch, it's safe to add it
https://react-redux.js.org/api/hooks#usedispatch

chore: Fix hook's warning about missing dependenies

---

locales/en.json
src/App.scss
src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
src/Components/SmartComponents/CVEs/CVEsTableToolbar.test.js
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTableToolbar.test.js.snap
src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTableToolbar.test.js.snap
src/Components/SmartComponents/SystemDetailsPage/__snapshots__/SystemDetails.test.js.snap
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.test.js
src/Components/SmartComponents/SystemsExposedTable/__snapshots__/SystemsExposedTable.test.js.snap
src/Components/SmartComponents/SystemsPage/SystemsTableToolbar.js
src/Helpers/TableToolbarHelper.js
src/Helpers/constants.js
src/Messages.js
src/Store/Reducers/CVEsStore.js
src/Store/Reducers/SystemsPageStore.js

To make it work on SystemsExposed page I had to move some props from InventoryTable to PrimaryToolbar. And I hate to do this but I had to remove 2 tests because I was not able to mount PrimaryToolbar inside InventoryTable in tests.

VULN-1512 feat: Filters reset

---

src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
src/Components/PresentationalComponents/KnownExploitSummary/KnownExploitSummary.js
src/Components/PresentationalComponents/KnownExploitSummary/__snapshots__/KnownExploitSummary.test.js.snap

Resolves [VULN-1683](https://issues.redhat.com/browse/VULN-1683).

VULN-1683 chore: Add identification to CVE detail cards elements

---

src/Components/PresentationalComponents/PaginationWrapper/PaginationWrapper.js
src/Components/SmartComponents/CVEs/CVEsTable.js
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap
src/Components/SmartComponents/SystemCves/SystemCveTable.js
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap

Was 32px TB, 48px RL; should be 16px TB, 24px RL.

fix(Bottom pagination): Remove double margin

---

src/Components/SmartComponents/SystemsPage/SystemsPage.js

VULN-1712 fix: Remove row action kebab in empty table

---

package-lock.json
package.json
src/Components/SmartComponents/Reports/Common/CVElabels.js
src/Components/SmartComponents/Reports/Common/__snapshots__/CVElabels.test.js.snap
src/Components/SmartComponents/Reports/Common/__snapshots__/firstPagePDF.test.js.snap
src/Components/SmartComponents/Reports/Common/__snapshots__/tablePage.test.js.snap
src/Components/SmartComponents/Reports/Common/styles.js
src/Components/SmartComponents/Reports/Common/tablePage.js
src/Components/SmartComponents/Reports/Executive/SecondPage.js
src/Components/SmartComponents/Reports/Executive/__snapshots__/SecondPage.test.js.snap

Waiting for FEC to update first.
Resolves [VULN-1646](https://issues.redhat.com/browse/VULN-1646).
[Mockup](https://marvelapp.com/prototype/5f47fef/screen/74054094)

VULN-1646 fix: Update appearence of labels in reports

---

package-lock.json
src/Components/SmartComponents/SystemsPage/SystemsPage.js

Fixes https://issues.redhat.com/browse/VULN-1740

fix systems pagination

---

src/Components/SmartComponents/Reports/ReportsPage.js

Fixes temp https://issues.redhat.com/browse/VULN-1680
The issue appears to be on platform side.  I removed temporarily `hideGlobalFilter` that caused the glitch. 
Once platform will solve the bug I'll revert th fix.

1680 Navigation glitch caused by hideGlobalFilter

---

locales/en.json
src/Components/SmartComponents/SystemsPage/SystemsPage.js
src/Helpers/constants.js
src/Helpers/constants.test.js
src/Messages.js
src/Store/Reducers/InventoryEntitiesReducer.js

For now without corresponding filter.

feat: Add OS column

---

src/App.scss
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap
src/Components/SmartComponents/InsightsSystemRule/InsightsSystemRule.js
src/Components/SmartComponents/InsightsSystemRule/__snapshots__/InsightsSystemRule.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTableToolbar.test.js.snap
src/Helpers/VulnerabilityHelper.js
src/Helpers/__snapshots__/VulnerabilityHelper.test.js.snap

Resolves [VULN-1592](https://issues.redhat.com/browse/VULN-1592).

VULN-1592 fix: Expanded table cells take up full width

---

package.json

fixes: https://issues.redhat.com/browse/VULN-1770

VULN-1770 chore: fix code coverage

---

package-lock.json
package.json

Should fix [VULN-1804](https://issues.redhat.com/browse/VULN-1804).

VULN-1804 chore: Bumb frontend-components-pdf-generator

---

locales/en.json
src/Components/SmartComponents/Reports/BuildExecReport.js
src/Components/SmartComponents/Reports/BuildExecReport.test.js
src/Components/SmartComponents/Reports/Executive/SecondPage.js
src/Components/SmartComponents/Reports/__snapshots__/BuildExecReport.test.js.snap
src/Helpers/constants.js
src/Messages.js

Resolves [VULN-1648](https://issues.redhat.com/browse/VULN-1648).

VULN-1648 fix: Add known exploits count to exec report CVSS table

---

src/Components/SmartComponents/SystemsPage/SystemsPage.js

Resolves [VULN-1800](https://issues.redhat.com/browse/VULN-1800).

fix(Systems page): Last seen sorting indicator on empty page

---

package-lock.json
package.json
src/Components/SmartComponents/Reports/Common/firstPagePDF.js
src/Components/SmartComponents/Reports/DownloadCVEsReport.js
src/Components/SmartComponents/Reports/DownloadSystemsReport.js
src/Helpers/MiscHelper.js
src/Helpers/ReportsHelper.js

Fonts and styles are slightly different but it's caused by the library.

VULN-1905 Fix PDF exports

---

src/Components/SmartComponents/Modals/BaseModal.js
src/Store/Reducers/CVEDetailsPageStore.js
src/Store/Reducers/CVEsStore.js
src/Store/Reducers/SystemDetailsPageStore.js

- props destructuring
- `useDispatch` instead of `connect` + `mapDispatchToProps`
- remove some unnecessary comments

refactor: Cleanup BaseModal component

---

src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTableToolbar.js
src/Components/SmartComponents/SystemsPage/SystemsPage.js
src/Helpers/Hooks.js
src/Store/Reducers/InventoryEntitiesReducer.js
src/Store/Reducers/reducersHelper.js

The PR might seem big but it's not. The second commit is the spit of the `SystemsExposedTable` into 2 components (Table and Toolbar). 
The PR is focused on resolving the select issues on pages we use inventory. Select kebab should work smoothly 
** Known issue: For systems exposed table when you select all, the `selectedRowsRawData` holds only the page data. (different ticket)  It uses the same logic as systems page which works. I believe it's connected to the `getEntities` cause that's the only difference the two components have, thus I'd like to merge this one first and work on delivering the `getEntities` for exposed systems

VULN-1861 Fix select issues in inventory page

---

src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Helpers/CVEHelper.js
src/Helpers/CVEHelper.test.js

PF handles the actions better now with the expandable rows

Fix(VULN-1978): Display all row actions

---

locales/en.json
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/Modals/ColumnManagementModal.js
src/Messages.js

As per [this document](https://docs.google.com/document/d/1UfljBFifu7uQahotfdnmijqcDuS-IsALNhTNxkRCy_g/edit#heading=h.2rye8eua9qiu).

feat: Add 'Reset to default' button to column management modal

---

src/Components/PresentationalComponents/KnownExploitSummary/__snapshots__/KnownExploitSummary.test.js.snap
src/Components/PresentationalComponents/Snippets/KnownExploitLabel.js
src/Components/PresentationalComponents/Snippets/__snapshots__/KnownExploitLabel.test.js.snap
src/Components/SmartComponents/Reports/Common/CVElabels.js
src/Components/SmartComponents/Reports/Common/__snapshots__/CVElabels.test.js.snap
src/Helpers/constants.js

fix: change 'known exploit' to 'Known exploit' for filter description

---

src/Helpers/DownloadReport.js
src/Helpers/DownloadReport.test.js

relates to fixes done in VULN-2003 and https://github.com/RedHatInsights/vulnerability-engine/pull/1157

fix: be consistent with backend max page size when doing report

---

package-lock.json
package.json
src/Components/SmartComponents/CVEs/CVEs.js
src/Components/SmartComponents/CVEs/CVEs.test.js
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Store/Reducers/InventoryEntitiesReducer.js
src/Store/Reducers/InventoryEntitiesReducer.test.js

Reverts RedHatInsights/vulnerability-ui#1384

Revert "VULN-2017 fix: Fix 2 API calls being made to fetch CVEs/systems"

---

src/Utilities/interceptors.js

Fixes: https://sentry.io/organizations/console-dot/issues/2828618283

fix: Don't try to toggle read only banner in Inventory

---

src/Helpers/Hooks.js

Fixes: https://sentry.io/organizations/console-dot/issues/2760240205

fix: Fix occasional crash with getEntities hook

---

src/Helpers/Hooks.js

Fixes: https://sentry.io/organizations/console-dot/issues/2760242556

fix: Gracefully handle RBAC API not operational

---

src/Utilities/interceptors.js

Mitigates [VULN-2125](https://issues.redhat.com/browse/VULN-2125).

fix: Fix crash when missing RBAC permissions

---

package-lock.json
package.json

chore: Update axios

---

src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/BusinessRiskFilter.test.js
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTableToolbar.test.js.snap
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTableToolbar.test.js.snap
src/Helpers/constants.js
src/Messages.js

VULN-2168: Added 'Critical' option to business risk

---

src/Components/SmartComponents/SystemDetailsPage/SystemDetails.js
src/Components/SmartComponents/SystemDetailsPage/SystemDetailsPage.js
src/Helpers/Hooks.js
src/Store/Reducers/SystemDetailsPageStore.js

fix: System detail page stuck on loading

---

src/App.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Components/SmartComponents/SystemsPage/SystemsPage.js

Reverts RedHatInsights/vulnerability-ui#1545

Revert "fix: Check for inventory perms on all pages"

---

src/Components/PresentationalComponents/CVEDetailsPageDescription/CVEDetailsPageDescription.js
src/Components/PresentationalComponents/CVEDetailsPageSummary/__snapshots__/CVEDetailsPageSummary.test.js.snap
src/Components/PresentationalComponents/CVETableExpandedCell/CVETableExpandedCell.js

fix: Only unknown or nullish description means no metadata

---

src/Components/PresentationalComponents/CVEDetailsPageSidebar/CVEDetailsPageSidebar.js
src/Components/PresentationalComponents/CVEDetailsPageSidebar/__snapshots__/CVEDetailsPageSidebar.test.js.snap
src/Components/PresentationalComponents/CVEDetailsPageSummary/CVEDetailsPageSummary.js
src/Components/PresentationalComponents/CVEDetailsPageSummary/__snapshots__/CVEDetailsPageSummary.test.js.snap
src/Components/PresentationalComponents/Snippets/SnippetWithPopover.js
src/Components/SmartComponents/CVEDetailsPage/CVEDetailsPage.js

[VULN-571](https://issues.redhat.com/browse/VULN-571)

feat(CVE detail page): Add edit status and BR buttons to popover

---

src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTableToolbar.js

[VULN-2041](https://issues.redhat.com/browse/VULN-2041)
Follow up to https://github.com/RedHatInsights/insights-remediations-frontend/pull/291

feat: Show modal when remediating manual items

---

src/App.js
src/Components/SmartComponents/Remediation/Remediation.js
src/Components/SmartComponents/SystemDetailsPage/SystemDetails.js
src/Components/SmartComponents/SystemDetailsPage/SystemDetailsPage.js

This should have no effect on the app.
Test cases:
- verify system detail page (go to systems and click on any system, now you're on system detail page) is loads expected, especially correct display name in header title and breadcrumb
- verify system include/exclude from system detail page is working correctly
- verify success notification is shown after completing remediation steps in remediations wizard

refactor: Remove `routerParams` and `connect`

---

locales/en.json
package-lock.json
package.json
src/Components/SmartComponents/Dashbar/Dashbar.js
src/Components/SmartComponents/Dashbar/Dashbar.test.js
src/Components/SmartComponents/Dashbar/__snapshots__/Dashbar.test.js.snap
src/Helpers/APIHelper.js
src/Messages.js

Added data fetching and skeleton loading for dashbar and announcements

feat: Dashbar add fetch data

---

src/Components/SmartComponents/LandingPage/LandingPage.js
src/Components/SmartComponents/LandingPage/__snapshots__/LandingPage.test.js.snap

updates version in links to docs so they resolve

 update doc urls

---

package-lock.json
package.json
src/Helpers/APIHelper.js
src/Helpers/constants.js
src/Store/Reducers/reducersHelper.js

Resolves [RHIF-23](https://issues.redhat.com/browse/RHIF-23).
Try to apply AAP or MSSQL workload from the global filter and check whether:
- CVE list page
- CVE detail page
- System list page
are affected by the filter, to check whether the filters are applied correctly you can use Network tab from the dev tools of your browser.

feat: Support AAP & MSSQL workloads

---

src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
src/Components/SmartComponents/CVEs/__snapshots__/CVEsTableToolbar.test.js.snap
src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTableToolbar.test.js.snap

Fixes [VULN-2196](https://issues.redhat.com/browse/VULN-2196).

fix: Disable expand all when table is empty

---

src/Components/PresentationalComponents/AdvisoryColumn/AdvisoryColumn.js
src/Components/PresentationalComponents/Filters/CustomFilters/TagFilter.js
src/Components/PresentationalComponents/Sorters/CustomSorters/SelectCustomSorter.js
src/Components/SmartComponents/Modals/ReportConfigModal.js
src/Components/SmartComponents/Modals/__snapshots__/ReportConfigModal.test.js.snap
src/Components/SmartComponents/Remediation/Remediation.js
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTableToolbar.js
src/Helpers/Hooks.js
src/Utilities/Routes.js

Reverts RedHatInsights/vulnerability-ui#1720

Revert "chore: Correct prop types"

---

locales/en.json
src/Components/PresentationalComponents/Snippets/NotVulnerableLabel.js
src/Helpers/constants.js
src/Messages.js

[VULN-2302](https://issues.redhat.com/browse/VULN-2302)
Displaying a label when conditions are met

feat(Exposed systems): Display 'Not vulnerable' label on affected but not vulnerable systems

---

src/Components/SmartComponents/Dashbar/Dashbar.js

As per https://docs.google.com/document/d/1IQ5BdyZApCYd_oz-RGIILJumrvI9RYMOWmaVA5bbloA page 7 and [VULN-2422](https://issues.redhat.com/browse/VULN-2422).
Updated Dashbar text font-family to Red Hat Display, font-weight to bold and font-size to 16px.

fix: Update Dashbar font

---

src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
src/Components/SmartComponents/SystemsPage/SystemsTableToolbar.js
src/Helpers/selectAllCheckboxHelper.js

CVE list table (2900 items):
Before: 2.82 s
After: 1.09 s
System list table (6700 items):
Before: 5.25 s
After: 2.09 s

Optimize bulk selection in CVE list and System list table

---

package-lock.json
package.json
src/Components/SmartComponents/CVEDetailsPage/__snapshots__/CveDetailsPage.test.js.snap

Associated Jira ticket: https://issues.redhat.com/browse/RHIF-111
This aligns the version of `redux` and `react-redux` libraries to the ones in insights-chrome.

chore(Shared dependencies): Align versions of redux

---

src/Components/PresentationalComponents/ErrorHandler/ErrorHandler.js
src/Components/PresentationalComponents/ErrorHandler/__snapshots__/ErrorHandler.test.js.snap
src/Components/SmartComponents/CVEDetailsPage/CVEDetailsPage.js
src/Components/SmartComponents/CVEs/CVEs.js
src/Components/SmartComponents/SystemDetailsPage/SystemDetails.js
src/Helpers/constants.js

Fixes `undefined` in the title of this error state.

fix: Fix service name missing in 403 empty state

---

src/Components/SmartComponents/SystemDetailsPage/SystemDetailsPage.js

Fixes: https://issues.redhat.com/browse/ESSNTL-4429
To test: 
1. Run the PR locally
2. visit a system detail page
3. observe you get proper detail page instead

 fix(ESSNTL-4429): pass inventroy id to detail wrapper

---

src/Components/SmartComponents/LandingPage/LandingPage.js

2022 --> 2023 so links to docs work

update docs url to 2023

---

src/Components/SmartComponents/SystemsPage/SystemsPage.js

- System list table started loading and didn't finish if you Enabled/disabled a system if you were on page 1
See recording on https://issues.redhat.com/browse/VULN-2663

Fix System list table not refreshing after disable/enable

---

src/Components/PresentationalComponents/Header/Breadcrumb.js
src/Components/PresentationalComponents/Header/Breadcrumb.test.js
src/Components/PresentationalComponents/Header/Header.test.js
src/Components/PresentationalComponents/Header/__snapshots__/Breadcrumb.test.js.snap
src/Components/SmartComponents/CVEDetailsPage/CVEDetailsPage.js
src/Components/SmartComponents/SystemDetailsPage/SystemDetailsPage.js

Ticket: https://issues.redhat.com/browse/VULN-2421

Simplify breadcrumbs

---

config/setupTests.js
src/Components/SmartComponents/SystemCves/SystemCves.js
src/Utilities/Routes.js

A partial cause of https://issues.redhat.com/browse/RHIF-207 is that the document title isnt updated properly. This PR introduces the chrome hook.
Associated Jira ticket: # (RHIF-266)
Navigate to the home page and the details page and verify that the document changes appropriately

fix(RHIF-263): adopt useChrome updateDocumentTitle hook

---

src/Components/SmartComponents/CVEs/CVEs.js
src/Components/SmartComponents/Dashbar/Dashbar.js
src/Components/SmartComponents/SystemCves/SystemCves.js

Surfaced after React 18 update.
https://issues.redhat.com/projects/VULN/issues/VULN-2743

Fix infinite loading bugs

---

src/App.js
src/Components/PresentationalComponents/StaticPages/UpgradePage.js
src/Utilities/Routes.js

https://issues.redhat.com/browse/VULN-2635
Also did a bit of refactoring to make it more readable.

Disable global filter on Reports page

---

src/Components/PresentationalComponents/TableColumns/SystemNameColumn.js
src/Helpers/constants.js

No Jira
Fixes System links in SystemsPage
How to test:
1. Make sure links redirect correctly on stable & preview

fix(SystemsPage): System link

---

src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap
src/Helpers/VulnerabilityHelper.js
src/Helpers/constants.js

https://issues.redhat.com/browse/VULN-2805

Sort by Advisory in detail tables

---

src/Components/SmartComponents/Dashbar/Dashbar.js

Ticket: https://issues.redhat.com/browse/VULN-2797
Mockups: https://www.sketch.com/s/4d721f7e-f57e-46e6-ba1c-739c0cad040e/v/RqpA2z/a/vR1qdgJ

Dashbar has tooltip and applies Advisory filter

---

src/Components/SmartComponents/CVEs/CVEsTableToolbar.js

https://issues.redhat.com/browse/VULN-2803

Remove Advisory filter upon feature flag disable

---

README.md
config/dev.webpack.config.js

This commit enables running the Vulnerabilities app together with other apps locally. The README is same as inventory, did not recreate the wheel :)

chore: enable route bind with local apps

---

src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
src/Components/SmartComponents/Dashbar/Dashbar.cy.js
src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
src/Components/SmartComponents/SystemCves/SystemCvesTableToolbar.test.js
src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTableToolbar.test.js.snap
src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
src/Helpers/constants.js
src/Store/Reducers/CVEDetailsPageStore.js
src/Store/Reducers/CVEsStore.js
src/Store/Reducers/SystemCvesStore.js

https://issues.redhat.com/browse/VULN-2804
Also fixes: https://issues.redhat.com/browse/VULN-2818
Adds "advisory_available: true" filter to CVE list page, CVE detail page and System detail pages if the CVEs without errata feature flag is enabled.

Apply advisory presence filter by default

---

src/Components/SmartComponents/SystemsPage/EdgeDevicesWarning.js
src/Components/SmartComponents/SystemsPage/SystemsPage.js
src/Helpers/APIHelper.js
src/Messages.js

With this PR, the systems pag shows an alert banner when there is a hidden immutable system 
Acceptance criteria:
- If the Account has No Immutable systems, [No changes to this page](https://www.sketch.com/s/ac25729e-df9b-4e74-a09c-badb62787d24/a/DEnMbYa#Inspect). 
- If the Account has at least one Immutable system, [show an alert stating they are not in this system list.](https://www.sketch.com/s/ac25729e-df9b-4e74-a09c-badb62787d24/a/Go8OqPD#Inspect)

feat(RHIF-304): show warning when there is an edge device

---

src/Components/SmartComponents/CVEDetailsPage/CVEDetailTableTitle.js
src/Components/SmartComponents/CVEDetailsPage/CVEDetailsPage.js
src/Components/SmartComponents/CVEDetailsPage/CveDetailTableTitle.test.js
src/Components/SmartComponents/CVEDetailsPage/CveDetailsPage.test.js
src/Helpers/APIHelper.js
src/Messages.js

This updates the CVE detail table title according to RHIF-297:
Acceptance criteria:
- When there is an immutable system, the title above the table should include the total number
- Total number should count both conventional and immutable systems
- when there is no immutable system, the title should have no change, and the total number

feat(RHIF-297): update cve detail table title

---

src/Helpers/APIHelper.js

Fixes broken stage-preview env by returning missing function

fix(SystemsPage): return useGetSingleDevice back

---

src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/ImmutableDevices.js

This adds missing @gkarat 's suggestions to previous PR https://github.com/RedHatInsights/vulnerability-ui/pull/2032/files

chore(ImmutableDevices): improve return condition

---

src/Utilities/VulnerabilityRoutes.js

Fixes: https://issues.redhat.com/browse/RHINENG-3765

fix(RHINENG-3765): Handle user missing inventory:hosts:read permission

---

src/Components/SmartComponents/LandingPage/LandingPage.js

Updates the doc links with new 1-latest subpath

chore(RHINENG-7106): update doc links with 1-latest

---

src/Components/PresentationalComponents/Filters/CustomFilters/CvssCustomFilter.js

This should fix the mobile version

fix: do not pass null value to checkbox component

---

package-lock.json

https://issues.redhat.com/browse/RHINENG-10628

chore(deps): Update express to fix a CVE

---

src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/PublishDateFilter.js
src/Components/SmartComponents/HybridInventory/HybridInventoryTabs.js
src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/ImmutableDevices.js
src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/ImmutableDevices.test.js

To test:
- Go to CVEs table
- Go to filter dropdown menu
- Choose Publish date filter
Filter should act the same as it currently does in stage.

fix(RHINENG-15842): Update conditionalFilterTypes

---

src/Components/SmartComponents/Modals/OsExposureReportModal/LifecycleSelect.js
src/Components/SmartComponents/Modals/OsExposureReportModal/LifecycleSelect.test.js
src/Components/SmartComponents/Modals/OsExposureReportModal/OsExposureReportModal.js
src/Components/SmartComponents/Modals/OsExposureReportModal/PdfExportButton.js
src/Components/SmartComponents/Reports/OsExposureReport/ExposureReportChart.js
src/Components/SmartComponents/Reports/OsExposureReport/ExposureReportTableRow.js

To test, navigate to Vulnerability -> Reports and use the "Report by operating system versions" report to test all of these changes:
- When you click the "Export PDF" button, kick the user out of the menu & show toast alerts.
- If confused, look at how the Report by CVEs flow works.
- Increase the spacing between RHEL OS minor versions and the chart legend in the pdf report
- Misalignment between the Critical columns in the pdf. All of the OS Name columns should be the same width in the tables for the pdf report

fix(RHINENG-18737): fix medium/low prio bugs

---

src/Components/SmartComponents/CVEs/CVEs.js
src/Helpers/constants.js

To test, to to Vulnerability -> CVEs. There should be an inline alert at the top of the table, as long as the conditions are met.
The text should be updated according to the Jira card.

fix(RHINENG-17801): Update CVEs alert
