RedHatInsights/vulnerability-ui

- .editorconfig
- src/Components/SmartComponents/CVEs/CVEs.js
- .editorconfig file to set up editor code style indention and charset
- VMAAS-239 CVSS Base Score table column header with tooltip on info icon: https://projects.engineering.redhat.com/browse/VMAAS-239
> VMAAS-239 Tooltip in table header, .editorconfig

- config/dev.webpack.config.js
- package-lock.json
- src/App.js
- src/Components/PresentationalComponents/CVEPageOverview/CVEPageOverview.js
- src/Components/SmartComponents/CVEPage/CVEPage.js
- src/Components/SmartComponents/CVEs/CVEs.js
- src/Components/SmartComponents/InventoryDetail/InventoryDetail.js
- src/Components/SmartComponents/SystemDetail/SystemDetail.js
- src/Components/SmartComponents/Systems/Systems.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Components/SmartComponents/Vulnerabilities/Vulnerabilities.js
- src/Components/SmartComponents/VulnerabilitiesTabs/VulnerabilitiesTabs.js
- src/Utilities/Routes.js
I had to remove all `routerParams` from application because it was causing problems with a lot of redirects. We should revisit this approach once we figure out which components needs to use `routerParams` and which should use `withRouter` so they do not cause multiple redirects.
> Fix routing by redirecting only on certain routes

- src/Components/SmartComponents/Vulnerabilities/Vulnerabilities.js
- src/index.html
Changed in page main header (required) and also in browser window title (assumed).
> VMAAS-285 Page titles changed

- src/index.html
We updated the ESI structure to allow more flexibility from chrome. This should fix the rendering issues with chrome
Related: https://projects.engineering.redhat.com/browse/RHIPLAT2-458
> Format index using new esi structure

- README.md
- config/base.webpack.plugins.js
- config/dev.webpack.config.js
- config/spandx.config.js
- config/webpack.common.js
- src/Utilities/Routes.js
- src/entry-dev.js
- src/entry.js
- src/index.html
You might have to run `npm run build` if you see errors with missing static files under `insights/platform`
> Update routing to match new version of cloud

- src/Helpers/APIHelper.js
this is a wild guess to fix https://projects.engineering.redhat.com/browse/VMAAS-490 just by reading the code
(I had no chance to run and test the code)
> allow data_format parameter for getAffectedSystemsByCVE API call

- src/Components/SmartComponents/CVEPage/CVEPage.js
- src/Components/SmartComponents/SystemDetail/SystemDetail.js
- src/Components/SmartComponents/Systems/Systems.js
- src/Components/SmartComponents/Vulnerabilities/Vulnerabilities.js
- src/Components/SmartComponents/VulnerabilitiesTabs/VulnerabilitiesTabs.js
- src/Components/SmartComponents/VulnerabilityHeader/VulnerabilityHeader.js
- src/Utilities/Routes.js
Apart from adding the "Systems" option in the breadcrumb, the PR contains: 
A small refactoring related to paths, I replaced the hardcoded titles with constants. 
Simplifying the functionality of the tabs, [patternfly](https://www.patternfly.org/v4/documentation/react/components/tabs/#props) now supports passing strings as `eventKey` .
> Add 'Systems' in breadcrumb

- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
If there's an only available affected system and it's the last page then on reload it resets the page to first one to avoid the out of range error.
> Fix out of range filter on reload

- src/Components/PresentationalComponents/DownloadReportKebab/KebabItems.js
- src/Components/SmartComponents/CVEs/VulnerabilitiesCves.js
- src/Components/SmartComponents/CVEs/VulnerabilitiesTable.js
- src/Components/SmartComponents/CVEs/VulnerabilitiesTableToolbar.js
- src/Components/SmartComponents/SystemCves/SystemCveTable.js
- src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
- src/Components/SmartComponents/SystemCves/SystemCves.js
- src/Store/Reducers/VulnerabilitiesStore.js
Add the option to expand/collapse all cve rows. The option is under the kebab toolbar. 
Expanded rows in vulnerability 
Systems details table
Expanded rows in system
Also, it respects the filtering and pagination.
> Add option to expand/collapse all cve rows in Vulnerability and System table

- src/Helpers/VulnerabilitiesHelper.js
add the missing label fort the system cve table
> Add description label in system table

- src/Components/SmartComponents/Modals/CvePairStatusModal.js
Strictly checking for `cveList.length === 1` returns undefined in case of editing multiple cves
Bug
Fix
> fix(pair-status): Fix bulk status editing  in system details page

- src/Helpers/constants.js
Bug-fix with ticket 795:    
Formatting of text on page when system is excluded from vulnerability analysis is  off
> bug-fix with ticket 795

- src/Components/SmartComponents/CVEPage/CVEPage.js
Adding the CVEs breadcrumb option for cve datail page
after 
before
> fix(breadcrumb): Add CVEs breadcrumb for cve detail page

- .travis/create_manifest.sh
- src/Components/SmartComponents/Reports/ExecutiveReport.js
As a result of displaying the executive pdf as A4 would be to have multi-pages in case of long CVE description
> fix(report): Display executive report as A4 (default)

- locales/translations.json
- src/Components/SmartComponents/Modals/CvePairStatusModal.js
- src/Components/SmartComponents/Modals/CveStatusModal.js
**CVE overall status modal**
- Info icon is too large. Change to 1.2em (currently 1.5)
- Missing cursor change when hovering over this tooltip (after "Not reviewed")
- Do not overwrite icon has no left margin
**CVE Pair status modal**
- Double spacing above checkbox should be removed
> fix(modals): StatusModal and PairStatusModal fixes

- locales/translations.json
- src/Components/PresentationalComponents/CVEPageDetails/__snapshots__/CVEPageDetails.test.js.snap
- src/Components/PresentationalComponents/CVEPageDetailsDescription/SnippetWithHeaderAndTooltip.js
- src/Components/PresentationalComponents/CVEPageDetailsDescription/__snapshots__/SnippetWithHeaderAndTooltip.test.js.snap
- src/Components/PresentationalComponents/CVEPageDetailsSeverity/CVEPageDetailsSeverity.js
- src/Components/PresentationalComponents/CvssVector/CvssVector.js
- src/Helpers/CVEHelper.js
- src/Helpers/CVEHelper.test.js
- src/Helpers/MiscHelper.js
- src/Helpers/MiscHelper.test.js
- src/Messages.js
1. Business risk & status should be blue to indicate tooltip
2. "Affected” should be changed to “Exposed”
3. ~spacing between the impact & base score. Should be 16px (md spacer)~ 
^^^ Fixed, but won't apply until Patternfly resolves this: https://github.com/patternfly/patternfly-next/issues/2725
4. Center Shield Icon 
5. Missing lines in CVSS popup - should be prop of the table component
6. Info icon color should be gray not blue
7. Padding to right of link with icon - Should be 8px (sm spacer)
> fix(UI): CVE detail page enhancement

- locales/translations.json
- src/Components/PresentationalComponents/Snippets/SnippetWithPopover.js
- src/Components/SmartComponents/SystemCves/SystemCves.js
- src/Helpers/constants.js
- src/Messages.js
1. Missing the “CVEs” title above the table
2. Columns in the table, Impact & base score should be reversed in order
3. Status should line up on the left - use a link style/get rid of button padding
the issue it's more obvious when we display the link, the alignment is off 
4. Status popover 
a)  ~Pair status should be a sentence case (ex Scheduled for patch, NOT scheduled for Patch)~ probably coming from back-end
b)  spacing bellow the "Justification note" and the horizontal line should be 16px (md spacer) 
c) The same applies to "CVE status" and the horizontal line. There should be a 16px spacer under the line
5. Excluded system page
a) icon size is wrong
b) replace RH Cloud Management Services with RH Insights
> fix(system-detail): Enhanced system detail page

- src/Components/SmartComponents/Modals/CveStatusModal.js
Fixes [issue](https://projects.engineering.redhat.com/browse/VMAAS-1019?focusedCommentId=2245204&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2245204) where clicking tooltip icon checks "Do not overwrite individual system status" checkbox on the status modal.
> fix(CVE status modal): Separated overwrite checkbox from tooltip

- src/Helpers/CVEHelper.js
inventory updated version, we are allowed to use node instead of callback that might cause reloads
> fix(inventory): Use node instead of callback

- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.test.js
- src/Helpers/constants.js
Fixing the commas and the reload issue when clicking on the associated cves
> fix(csaw): Fix associated cve links in csaw rule box

- src/Components/SmartComponents/CVEs/VulnerabilitiesTableToolbar.js
- src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
- src/Components/SmartComponents/Systems/Systems.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
**Fixes [VMAAS-1045](https://projects.engineering.redhat.com/browse/VMAAS-1045) and [VMAAS-1050](https://projects.engineering.redhat.com/browse/VMAAS-1050).** 
**Previous behaviour:** 
**CVEs table:** Kebab was disabled when table was empty which prevented from bulk editing status and business risk when there were items selected but filtered out.
**System CVEs table and Systems exposed table:** Disabled kebab prevented from bulk editing pair status of selected but filtered out items.
**Systems table:** Disabled kebab prevented from toggling between showing and hiding excluded systems when table was empty.
**New behaviour:**
**All tables:** Disable export to CSV and export to JSON buttons when table is empty.
**CVEs table, System CVEs table and Systems exposed table:** Disable kebab only …
> fix(kebab-menus): Don't disable kebab menus when table is empty and there is an action

- src/Components/PresentationalComponents/DownloadReportKebab/KebabItems.js
- src/Components/SmartComponents/CVEs/VulnerabilitiesTableToolbar.js
- src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
Fixes [VMAAS-1147](https://projects.engineering.redhat.com/browse/VMAAS-1147).
1. Select any CVE in Vulnerability/CVE by system page
2. Filter out all CVES
**previous:**
Expand all item in toolbar kebab was enabled but didn't do anything
**new:**
Expand all item in toolbar kebab is disabled
> fix(cve tables): Expand all button disables when no data

- src/Components/PresentationalComponents/Snippets/__snapshots__/SnippetWithPopover.test.js.snap
Fixes tests failing due to https://github.com/RedHatInsights/vulnerability-ui/commit/55b784a04e667bc2d3930672547219fbcf1e58c1 being applied before https://github.com/RedHatInsights/vulnerability-ui/commit/8eae4c57cc6a11f560020f25b828710b7419699a
> chore(tests): Fixed snippet with popover snapshot test

- package.json
now you can use:
1. `npm run test-watch ` to watch your tests while you're writing tests
2.  `npm run test-updateSnapshot` to update snapshots
> chore(npm scripts): Add npm scripts for running  tests

- src/Components/SmartComponents/Modals/CvePairStatusModal.test.js
- src/Components/SmartComponents/Modals/CveStatusModal.test.js
It doesn't check whether setSystemCveStatus() was called correctly for the status modal, I haven't figured out testing promise chaining yet.
> chore(test): Added unit test for both status modals

- src/Components/SmartComponents/Modals/CvePairStatusModal.js
- src/Components/SmartComponents/SystemCves/SystemCves.js
- src/Helpers/CVEHelper.js
- src/Helpers/VulnerabilitiesHelper.js
Fixes [VULN-132](https://projects.engineering.redhat.com/browse/VULN-132).
- pass missing overall justification param necessary for the fix
- refactor getCvestatus -> getCveStatus
- simplify getCveStatus
- handle overall checkbox change inside hook
> fix(pair status modal): Show CVE justification note when using overall

- package-lock.json
- package.json
- src/Components/SmartComponents/CVEs/VulnerabilitiesTableToolbar.js
- src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
- src/Components/SmartComponents/Systems/SystemsTableToolbar.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
After
for the exposed table toolbar it disables the `DropdownItem` .  the inventory needs to update the version of the FEC
connected to the PR: https://github.com/RedHatInsights/frontend-components/pull/526
> fix(export button) Disable button on empty page

- src/Helpers/APIHelper.js
After vulnerabilities-client has been updated, uuid = false is added to the endpoint /v1/systems. it was because the order of parameters sent to vulnerability client was influenced. I added 'uuid' to parameterNames array to make it even with API parameters from backend.
> fix(SystemsPage) unwanted uuid filter is added on systems page onload

- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleSummary.js
- src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
- src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleSummary.test.js.snap
- src/Components/PresentationalComponents/CVEInfoBox/CVEInfoBox.js
- src/Components/PresentationalComponents/CVEInfoBox/__snapshots__/CVEInfoBox.test.js.snap
- src/Components/PresentationalComponents/CVEPageDetails/CVEPageDetails.js
- src/Components/PresentationalComponents/CVEPageDetails/__snapshots__/CVEPageDetails.test.js.snap
- src/Components/PresentationalComponents/CVEPageDetailsDescription/CVEPageDetailsDescription.js
- src/Components/PresentationalComponents/CVEPageDetailsDescription/__snapshots__/CVEPageDetailsDescription.test.js.snap
- src/Components/PresentationalComponents/CVEPageDetailsSeverity/CVEPageDetailsSeverity.js
- src/Components/PresentationalComponents/CVEPageDetailsSeverity/__snapshots__/CVEPageDetailsSeverity.test.js.snap
- src/Components/PresentationalComponents/CVETableExpandedCell/CVETableExpandedCell.js
- src/Components/SmartComponents/Modals/BusinessRiskModal.js
- src/Components/SmartComponents/Modals/CvePairStatusModal.js
- src/Components/SmartComponents/Modals/CveStatusModal.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
Part of [VULN-1066](https://projects.engineering.redhat.com/browse/VULN-1066).
- CVEPageDetailsDescription item spacing
- CVEPageDetailsSeverity item spacing
- impact and base score box spacing
- table title bottom padding
https://marvelapp.com/75dcb1j/screen/58397731
> fix(layout): Fixed spacing after PF4 migration

- package.json
The intetion is to publish the npm package when the code is stable `ci-stable` and publish a bete version on master
> chore(semantic-release): Add workflow publication

- config/rollup.config.js
- package-lock.json
- package.json
- src/Components/SmartComponents/SystemCves/SystemCves.js
- src/Helpers/MiscHelper.js
- src/Helpers/MiscHelper.test.js
- src/index.js
This PR re-introduces wrapped SystemCves to properly show translated Cves table, it also wraps the component in Router if parent component requires it.
I had some proplems with using the component and turns out the react-router-dom was not playing nicely with `useLocation` and `useHistory` used browser's one instead.
This PR also changes rollup slightly to allow direct import of `SystemCvesStore` so we don't have to import entire component just for the store.
> fix(detail): wrap detail in router and use location and history from browser

- src/Components/SmartComponents/InventoryDetail/InventoryDetail.js
- src/Components/SmartComponents/Systems/Systems.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
We are working on inventory refactoring, since we'd like to fully use hooks and such we have to use App's react dependency. With this being used react-redux needs to be passed from application as well. If you are cautious about the size of your bundle I can pick only the functions really required by inventory.
> feat(inventory): pass react-redux to inventory

- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
- src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
- src/Messages.js
- Outlined question circle icon's tooltip should toggle on both click and hover
- Space between "ansible remediation" and "risk of change" should be 16px between
> fix(csaw rulebox): Fix spacing and tooltips

- src/Components/SmartComponents/Reports/BuildExecReport.js
- src/Helpers/constants.js
Executive report breakdown by CVSS with zero CVEs with N/A CVSS
Executive report breakdown by CVSS with at least one CVE with N/A CVSS
> fix: include N/A CVSS CVEs in executive report

- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleSummary.js
- src/Helpers/constants.js
Fixes [VULN-1121](https://projects.engineering.redhat.com/browse/VULN-1121) - remove read more label if text is short enough, but only for Summary because Rulebox is using read more as a link.
> fix(csaw summary): Don't show read more if there is nothing to show

- src/Components/PresentationalComponents/CVEInfoBox/CVEInfoBox.scss
- src/Components/PresentationalComponents/CvssVector/CvssVector.scss
Fixes [VULN-1114](https://projects.engineering.redhat.com/browse/VULN-1114).
- Add background to the infobox (using bgcolor-200 which is a bit darker then previous bgcolor-150, which was removed by patternfly)
- Fix h6 (bold labels) having bottom margin
> fix(CVE detail header): Fixed infobox styling

- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
Fixes commit 7c2ae0d88e961bbeebe37098ffa7de52613b7d6c which has introduced a regression where selecting and trying to edit status of multiple systems from system exposed table would not load any system id, which would result in no op when changing status/justification and clicking save.
> fix(system exposed table): Fixed bulk edit status regression

- locales/data.json
- src/Components/PresentationalComponents/CVEPageDetailsDescription/CVEPageDetailsDescription.scss
And also capped the column size to prevent the label from wrapping.
> fix(status breakdown table): Rename "count" to "num. systems"

- src/Components/SmartComponents/SystemCves/SystemCveTable.js
- src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
- src/Components/SmartComponents/SystemCves/SystemCves.js
- src/Components/SmartComponents/SystemDetailsPage/SystemDetails.js
- src/index.js
Solves: [VULN-951](https://projects.engineering.redhat.com/browse/VULN-951).
Logic: 
> Pages receive what kind of actions are allowed to display for users as a prop type of array
> The page display only allowed action (show status/business risk modals, remediation ...)
I could not verify on Inventory, but I believe just an update should be enough
> feat(paper-cut):  remove Edit Status

- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Components/SmartComponents/SystemsPage/SystemsPage.js
`Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render. ` error resolved in CVEDetails and Systems pages
> fix(SystemsExposed) Maximum update depth exceeded error resolved

- src/Components/SmartComponents/SystemDetailsPage/SystemDetailsPage.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Components/SmartComponents/SystemsPage/SystemsPage.js
There is a new feature brewing in chrome, building chrome with webpack [1]. This PR passes newly required dependencies. In future we'll use Federated modules [2] so there won't be a need for these changes, but this is required as a mid-step solution.
Also, for enabling A/B testing of inventory detail we are working on new inventory component, for now this component will be undefined so use `React.Fragment` as fallback.
[1] https://github.com/RedHatInsights/insights-chrome/pull/842
[2] https://webpack.js.org/concepts/module-federation/
> Pass pf react core to inventory to properly render inventory

- src/Components/SmartComponents/Reports/BuildExecReport.js
- src/Components/SmartComponents/Reports/DownloadExecutive.js
[overflowBefore.pdf](https://github.com/RedHatInsights/vulnerability-ui/files/5005719/overflowBefore.pdf)
[overflowAfter.pdf](https://github.com/RedHatInsights/vulnerability-ui/files/5005720/overflowAfter.pdf)
possible fix for: [VULN-634](https://projects.engineering.redhat.com/browse/VULN-634) 
[notOverflow.pdf](https://github.com/RedHatInsights/vulnerability-ui/files/5005730/notOverflow.pdf)
> fix(ExecutiveReport): overwflow is moved to second page

- src/Helpers/MiscHelper.js
- src/Helpers/MiscHelper.test.js
- src/Helpers/constants.js
Fixes [VULN-1170](https://projects.engineering.redhat.com/projects/VULN/issues/VULN-1170).
Also refactors `substractDays` and `substractYears` inside `constants.js` file to `subtractDays` and `subtractYears`.
**Explanation:**
Inside `MiscHelper.js > formatDate` function month was get using [`date.getMonth` function which returns month but zero indexed](https://www.w3schools.com/jsref/jsref_getmonth.asp). This subtracted a month from the date which not only showed incorrect CVEs for the timespan but could create error in case the previous month didn't have day number of today (31st of June for example).
**Testing setup:**
I mocked today's date inside `currDate` default parameter (remember month is zero indexed here too) inside `constants.js > subtractYears` and `subtractDays` function. …
> fix(filtering): Correctly format month of publish date

- package-lock.json
- package.json
Fixes [VULN-1193](https://projects.engineering.redhat.com/browse/VULN-1193) and unblocks [VULN-1061](https://projects.engineering.redhat.com/browse/VULN-1061) and subsequently https://github.com/RedHatInsights/vulnerability-ui/pull/513.
> chore(packages): Bump FCE PDF generator

- locales/data.json
- locales/translations.json
- src/Components/SmartComponents/Modals/ReportConfigModal.js
- src/Components/SmartComponents/Reports/DownloadCVEsReport.js
- src/Helpers/constants.js
- src/Messages.js
Fixes [VULN-1231](https://projects.engineering.redhat.com/projects/VULN/issues/VULN-1231).
> fix(PDF report): Restrict user note char count and adjust item count to fit page

- locales/data.json
- locales/translations.json
- src/Components/SmartComponents/Reports/BuildExecReport.js
- src/Components/SmartComponents/Reports/Common/firstPagePDF.js
- src/Components/SmartComponents/Reports/Common/styles.js
- src/Components/SmartComponents/Reports/Common/tablePage.js
- src/Components/SmartComponents/Reports/DownloadCVEsReport.js
- src/Components/SmartComponents/Reports/ReportsHelper.js
- src/Messages.js
Fixes [VULN-1061](https://projects.engineering.redhat.com/browse/VULN-1061).
Currently asterisk is shown inside the footer, but first CVE with security rule doesn't have asterisks, see comment.
> fix(PDF report): Add footer

- src/Components/SmartComponents/Modals/CvePairStatusModal.js
- src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
Fixes subtask 4 from [VULN-1181](https://projects.engineering.redhat.com/projects/VULN/issues/VULN-1181).
Steps:
1. Go to System detail table
2. Edit 2 CVEs status - uncheck "Use overall CVE status" and set justification note to the same string, e.g. "note"
Previously if you would select and bulk edit these 2 CVEs (or even selected one of them and edited status from toolbar kebab menu), the justification note would be blank even thought it should be the string you have previously chosen, now it correctly shows the note (case 4 right from [mockup](https://marvelapp.com/prototype/75dcb1j/screen/62253695)).
> fix(status edit): Pass justification note when bulk editing

- src/Helpers/constants.js
Has to be merged after https://github.com/RedHatInsights/vulnerability-engine/pull/752 is merged for functionality.
> fix: use display name for sotring on systems exposed page

- src/Components/SmartComponents/SystemsPage/SystemsPage.js
In order to show proper RBAC state in systems table we need to pass `fullView` prop to inventory component. This applies only to systems page as it's only place where inventory table is just one component on screen. Without this prop the `unAuthorized` component would be in table, which is not correct based on our mocks.
[1] https://github.com/RedHatInsights/frontend-components/blob/master/packages/inventory/doc/inventory.md#using-rbac-with-inventory
> feat(systems): set systems table to full view

- locales/en.json
- package-lock.json
- package.json
- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.test.js
- src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
- src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/SecurityRuleFilter.js
- src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/SecurityRuleFilter.test.js
- src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
- src/Components/SmartComponents/CVEs/__snapshots__/CVEsTableToolbar.test.js.snap
- src/Components/SmartComponents/Modals/ReportConfigModal.js
- src/Components/SmartComponents/Reports/ReportsHelper.js
- src/Components/SmartComponents/Reports/__snapshots__/ReportsPage.test.js.snap
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTableToolbar.test.js.snap
- src/Components/SmartComponents/SystemDetailsPage/__snapshots__/SystemDetails.test.js.snap
- src/Components/SmartComponents/SystemsExposedTable/__snapshots__/SystemsExposedTable.test.js.snap
- src/Helpers/APIHelper.js
- src/Helpers/TableToolbarHelper.js
- src/Helpers/TableToolbarHelper.test.js
- src/Helpers/constants.js
- src/Messages.js
- src/Store/Reducers/CVEDetailsPageStore.js
Fixes [VULN-909](https://issues.redhat.com/projects/VULN/issues/VULN-909).
Removes uses of `security_rule` API param to unblock [VULN-1267](https://issues.redhat.com/projects/VULN/issues/VULN-1267).
SecurityRuleFilter component test coverage stays 100%.
> fix(filters): Fix security rule filter to use checkboxes

- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleSummary.js
- src/Components/PresentationalComponents/CVEPageDetailsSeverity/CVEPageDetailsSeverity.js
- src/Components/SmartComponents/Reports/Common/tablePage.js
- src/Helpers/CVEHelper.js
- src/Helpers/CVEHelper.test.js
- src/Helpers/DownloadReport.js
- src/Helpers/DownloadReport.test.js
- src/Helpers/VulnerabilityHelper.js
- src/entry-dev.js
- src/entry.js
This is a part of a larger effort to remove PF background images from chrome build. Old imports were referencing UMD versions of FCE packages which indirectly leads to importing the whole "@patternfly/react-core" package and that injects PF about modal background images to chrome build. And those are pretty big.
cc @jiridostal @katerinapat can you please verify that this does not introduce any bugs?
> Fix UMD imports in FCE packages.

- src/Components/SmartComponents/Reports/Common/firstPagePDF.js
- src/Components/SmartComponents/Reports/Common/styles.js
- src/Components/SmartComponents/Reports/ReportsPage.js
- src/Components/SmartComponents/Reports/__snapshots__/ReportsPage.test.js.snap
> fix(Reports): Align chart pie icon and fix missing newline

- src/App.js
No need to use `globalFilterScope` as this is meant to fetch tags, SIDs and workloads for `registered_with` parameter. Also use newer way of consuming global filter data, if we pass 3rd parameter to `mapGlobalFilter` it will automatically group workloads, SID and tags to specific groups so we don't have to filter out certain parts of it.
> fix(global filter): when consuming global filter no need to pass scope

- src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
- src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap
- src/Helpers/constants.js
Fixes [VULN-1314](https://issues.redhat.com/browse/VULN-1314).
I had to revert non-wrapping of CVE synopsis, because description is in the same column as synopsis which applied non-wrap to it and this caused the table to stretch. From my testing the synopsis does wrap pretty well either way, it never wraps like this [(VULN-1307)](https://issues.redhat.com/browse/VULN-1307):
Maybe it wraps uglily in different browser or different setup, then we can find other workaround to VULN-1307.
> fix(CVE tables): Fixed table stretching when expanding description

- src/App.scss
- src/Components/SmartComponents/Modals/ReportConfigModal.js
- src/Components/SmartComponents/Reports/__snapshots__/ReportsPage.test.js.snap
Increased width from 35rem to 40rem to closer resemble mockup, none of the modal variants:
- small (35rem)
- medium (52.5rem)
- large (70rem)
do not fit the mockup, even if they did in our current version of patternfly only the small variant is working correctly.
> fix(report config modal): Increased width of the modal

- locales/en.json
- package-lock.json
- package.json
- src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/SearchFilter.js
- src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
- src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTableToolbar.test.js.snap
- src/Components/SmartComponents/SystemDetailsPage/__snapshots__/SystemDetails.test.js.snap
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Components/SmartComponents/SystemsPage/SystemsTableToolbar.js
- src/Helpers/APIHelper.js
- src/Helpers/TableToolbarHelper.js
- src/Helpers/constants.js
- src/Messages.js
Resolves [VULN-1331](https://issues.redhat.com/browse/VULN-1331). When filtering advisories total number of items is incorrect and also you have to specify the full name of the advisory to be able to filter by it - both of these are backend issues and are addressed in [VULN-1337](https://issues.redhat.com/projects/VULN/issues/VULN-1337).
> feat(filtering): Add filtering by advisory for system CVE table

- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
The param sort is lost when changing pagination, use the value stored in redux in such case
> VULN-1301 fix(cve details page): Fix undefined sort param

- src/Components/SmartComponents/Modals/CvePairStatusModal.js
- src/Components/SmartComponents/Modals/CvePairStatusModal.test.js
- src/Components/SmartComponents/SystemCves/SystemCves.js
- src/Components/SmartComponents/SystemCves/SystemCves.test.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
Fixes [VULN-1181](https://issues.redhat.com/browse/VULN-1181).
[Expected behaviour mockups](https://marvelapp.com/prototype/75dcb1j/screen/62253695?).
This applies to both CVE detail and System detail pages.
- fix default states from the mockup, almost all were incorrect before
- refactor conditions and variable names  to improve readability
- moved logic for displaying "Selected pair have different statuses..." warning to Pair status modal file
> Fix(pair status modal): Enhance and refactor CVE pair status modal

- src/Components/SmartComponents/CVEs/CVEsTable.js
> fix(loading): Don't crash on CVE page when API is unreachable

- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.scss
- src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
- src/Helpers/constants.js
1.  refactor a bit the component. Use classes instead of styles
2. use PF label for the risk of change
> VULN-1378 fix(csaw box): Use PF label for risk of change

- src/Components/PresentationalComponents/StaticPages/NoAccessPage.js
- src/Components/PresentationalComponents/StaticPages/UpgradePage.js
- src/Components/SmartComponents/CVEDetailsPage/CVEDetailsPage.js
- src/Components/SmartComponents/Reports/ReportsPage.js
- src/Components/SmartComponents/Reports/__snapshots__/ReportsPage.test.js.snap
- src/Components/SmartComponents/SystemDetailsPage/SystemDetailsPage.js
- src/Components/SmartComponents/SystemDetailsPage/__snapshots__/SystemDetailsPage.test.js.snap
Fixes [VULN-1375](https://issues.redhat.com/browse/VULN-1375).
Insight application is using PF Page component to wrap the whole page (top toolbar, left side navbar and vuln app) and Vulnerability app was using PF Page component to wrap its content (for example header and CVE table). And to my understanding you should not nest Page, only use it for the outside (whole) page. I checked and neither Drift and Compliance are using Page inside them. I did some testing and found no side effects.
Changing this fixed the problem with global filter and might prevent more bugs in the future.
> fix(global filter): Fix global filter disappearing when closing popup

- src/Components/SmartComponents/Remediation/Remediation.js
- src/Components/SmartComponents/SystemCves/SystemCveTable.js
- src/Components/SmartComponents/SystemDetailsPage/SystemDetailsPage.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
we can finally use optional chaining and accessing non-camelcase variables without warnings
> chore(clean up): Clean up eslint-disable comments

- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
- src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
- src/Components/SmartComponents/Modals/CvePairStatusModal.js
- src/Components/SmartComponents/Modals/CveStatusModal.js
[SPUR page 1](https://docs.google.com/document/d/1z-T2LHa5_BWxle9DFEW7ENobZSWYC9UH4F6GI5jLluU/edit#heading=h.462qnblhrcga)
Before:
Tooltips shown on hover, hiden on click
After:
Tooltips shown on hover, click has no effect
> fix: Fix tooltip behaviour on click

- src/Components/SmartComponents/Modals/ReportConfigModal.js
- src/Components/SmartComponents/Modals/__snapshots__/ReportConfigModal.test.js.snap
- src/Components/SmartComponents/Reports/DownloadExecutive.js
- src/Components/SmartComponents/Reports/ReportsPage.js
- src/Components/SmartComponents/Reports/__snapshots__/ReportsPage.test.js.snap
Disable export button on the report config modal and prevent user from exporting the report if:
- user note is too long
- CVSS score filter is < 0, > 10, or min > max
Also fix some errors from the console.
> fix(Reports page): Disable export button if config is invalid

- locales/en.json
- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleSummary.js
- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleSummary.test.js
- src/Components/PresentationalComponents/CVETableExpandedCell/CVETableExpandedCell.js
- src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
- src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap
- src/Messages.js
Fixes [VULN-1275](https://issues.redhat.com/browse/VULN-1275).
[Mockup link](https://marvelapp.com/prototype/5f47fef/screen/75473599)
This includes:
- replacing `Description` label with `CVE description`
- replacing multiple `Read more` links with one `View more info about this CVE`
- adding `View more info about this CVE` link to expanded desc of CVEs without security rule
- spacing improvements
This does not include:
- replacing security rule icons with insight-labels
> VULN-1275 feat: Update CSAw summary to new mockups

- src/Components/SmartComponents/Reports/DownloadCVEsReport.js
- src/Helpers/constants.js
[SPUR page 6](https://docs.google.com/document/d/1z-T2LHa5_BWxle9DFEW7ENobZSWYC9UH4F6GI5jLluU/edit#)
CVE report was using status/BR/impact label from response, bypassing intl. I fixed this by reading status/BR/impact ID from the response and mapping translated label on our side.
This has two improvements:
- in english labels are not using title case (Not Reviewed -> Not reviewed)
- they are translatable
I was a bit concerned about the performance, so I did some tests, but there seems to be no slowdown from this change.
> feat(CVE report): Translate status, business risk and impact options

- src/Components/SmartComponents/Reports/BuildExecReport.js
- src/Helpers/MiscHelper.js
Insert the second page only if it has CVEs to display. 
also, some enhancements to avoid running `topCvesPerPage` function twice
[vulnerability_executive-report--2021-01-07(18).pdf](https://github.com/RedHatInsights/vulnerability-ui/files/5782202/vulnerability_executive-report--2021-01-07.18.pdf)
> VULN-1369 fix(executive report): Do not render 2nd page if it's empty

- src/Components/PresentationalComponents/CVETableExpandedCell/CVETableExpandedCell.js
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap
Tests are failing because they can't find rules in expanded CVE
> chore: bring back rule div class

- src/App.js
Fixes [VULN-1487](https://issues.redhat.com/browse/VULN-1487).
I fixed this but was a bit confused why the previous button stayed gray until I clicked somewhere else, but this is actually correct because that button is the last clicked upon so it had focus.
> VULN-1487 fix(navigation): Highlight correct nav button upon navigating back

- package-lock.json
- package.json
frontend-components-remediations were previously pulling a package vulnerable to CVE-2020-26291, newer version of f-c-r is no longer doing that
> fix: update vulnerable package version

- locales/en.json
- src/Components/PresentationalComponents/EmptyStates/EmptyStates.js
- src/Components/PresentationalComponents/ErrorHandler/ErrorHandler.js
- src/Components/PresentationalComponents/StaticPages/NoAccessPage.js
- src/Components/SmartComponents/CVEs/CVEs.js
- src/Components/SmartComponents/CVEs/CVEs.test.js
- src/Components/SmartComponents/SystemCves/SystemCves.js
- src/Components/SmartComponents/SystemCves/SystemCves.test.js
- src/Components/SmartComponents/SystemsPage/SystemsPage.js
- src/Helpers/VulnerabilityHelper.js
- src/Messages.js
Fixes [VULN-1388](https://issues.redhat.com/browse/VULN-1388).
CVE page and system CVE page used to crash because of clearing notification on error response, which caused maximum update depth error. I moved the clear notifications function to unmounting, added 502 status code to switch and rearanged them descending in the switch.
Added 403 (unauthorized) error handler.
Error handling should be correct on all pages except CVE detail page, see [VULN-1365](https://issues.redhat.com/browse/VULN-1365).
> fix(CVE page): Handle errors gracefully

- config/dev.webpack.config.js
- config/prod.webpack.config.js
- profiles/local-frontend.js
@leSamo, @tkasparek 
FYI if you want to run `/beta/insights/vulnerability` you should run the 
- `npm run start:beta` --> `ci.foo...../beta/..`
- `npm run prod:beta` --> `prod.foo..../beta/..`
The command without `:beta` running against stable chrome, inventory, platform ..etc, like
- `npm run start` --> `ci.foo...../insights/..`
> chore(config): Fix local development configurations

- package-lock.json
- package.json
- src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/SearchFilter.js
- src/Components/SmartComponents/CVEDetailsPage/CveDetailsPage.test.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.test.js
- src/Components/SmartComponents/SystemsPage/SystemsPage.js
- src/Store/Reducers/SystemsPageStore.js
I'm not 100% happy with the solution but for now it should be okay and it will unblock the other tickets.
dispatching several times the action to change the params was causing the  error `Maximum update depth exceeded`. On every single action it tried to update the view (in short time) even though the parameters were the same. 
For that reason, I used a deep object comparison for the parameters which checks the keys and the values and fires the effect(request) only if the parameters **really** change
`CHANGE_EXPOSED_SYSTEMS_PARAMETERS` is dispatched only once on first load.
> VULN-1453 fix(systems maximum update): Use deep comparison for params

- src/App.scss
- src/AppEntry.js
@leSamo This simple layout change has worked for me locally. Can you double-check it covers all use cases with no regressions?
Chrome 2 uses the CSS class to fix the problem. Chrome 1 however (non-beta envs until summit) needs adding the style to the root element. We can allow that in old chrome because there is no client-side routing between apps so the style is discarded when navigatin. The effect will be obsolete after the summit.
I've check bot ci beta and stable envs and the sticky header is in both.
> Fix sticky header layout.

- src/App.scss
- src/Components/PresentationalComponents/Filters/CustomFilters/CheckboxCustomFilter.js
- src/Components/PresentationalComponents/Filters/CustomFilters/CvssCustomFilter.js
- src/Components/PresentationalComponents/Filters/CustomFilters/RadioCustomFilter.js
- src/Components/SmartComponents/Modals/ReportConfigModal.js
- src/Components/SmartComponents/Modals/__snapshots__/ReportConfigModal.test.js.snap
- src/Components/SmartComponents/Reports/CustomReportFilter.js
- src/Components/SmartComponents/Reports/ReportsHelper.js
- src/Components/SmartComponents/Reports/__snapshots__/ReportsPage.test.js.snap
Fixes [VULN-1508](https://issues.redhat.com/browse/VULN-1508).
- CVSS filter shouldn't be validated when user leaves "from" or "to" field empty (leads to NaN error)
- styles not applying to config modal because it was mounted outside #root elements
- If the selected options are too long select box overflows awkwardly
- Selecting all items in checkbox filter should not add segment to first PDF page intro string
- Radio missing id console error
> VULN-1508 fix(Report modal): Fix multiple minor bugs

- src/Components/SmartComponents/Reports/BuildExecReport.js
- src/Components/SmartComponents/Reports/__snapshots__/BuildExecReport.test.js.snap
Fixes [VULN-1564](https://issues.redhat.com/browse/VULN-1564).
Problem was that first column of legend table was higher CVSS score to lower and the second one was in reverse order.
> VULN-1564 fix(exec report): Fix CVEs by CVSS score chart legend

- src/Components/SmartComponents/CVEDetailsPage/CVEDetailsPage.js
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTableToolbar.test.js.snap
- src/Helpers/VulnerabilityHelper.js
- src/Helpers/VulnerabilityHelper.test.js
- src/Helpers/__snapshots__/VulnerabilityHelper.test.js.snap
- fix `VulnerabilityHelper` snapshot being on one line and hard to read
- fix proptypes errors with `hasExploit` and `hasRule` in `GroupedCVELabels` which expects booleans, if you don't like the `!!truthyValue` to boolean conversion, let my know
> chore: Cleanup GroupedCVELabels

- src/App.scss
> fix: Fix tag icon size and spacing

- .eslintrc.yml
- src/App.js
- src/Components/PresentationalComponents/CVETableExpandedCell/CVETableExpandedCell.js
- src/Helpers/VulnerabilityHelper.js
Finally it compiles when you wither use console or an unused variable so I brought back the eslint rules for those 2. 
We missed in few places the unused variable so I fixed them
> chore: Fix lint warnings

- config/dev.webpack.config.js
- config/prod.webpack.config.js
- src/Components/SmartComponents/SystemCves/SystemCves.js
- src/index.js
Since we can now use federated modules in every environment let's share the system detail with it. This way we don't have to maintain the version of it in all environments, it's the same for all users on one environment. If a bug is found the fix is deployed just in this application and propagated to inventory via federetad modules.
```JSX
import React, { useContext } from 'react';
import AsyncComponent from '@redhat-cloud-services/frontend-components/AsyncComponent';
import { RegistryContext } from '../../store';
import { useRouteMatch } from 'react-router-dom';
const AdvisorTab = () => {
const { params } = useRouteMatch('/:inventoryId');
return <AsyncComponent
appName="vulnerability"
module="./SystemDetail"
getRegistry={useContext(RegistryContext).getRegistry}
customItnlProvider …
```
> feat(system detail): use federated modules to share system detail

- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Components/SmartComponents/SystemsExposedTable/__snapshots__/SystemsExposedTable.test.js.snap
- src/Components/SmartComponents/SystemsPage/SystemsPage.js
This will ensure that a newer version of insights inventory table would not break columns.
> Disable default columns on inventory table

- src/Components/SmartComponents/SystemsPage/SystemsPage.js
- src/Helpers/constants.js
This refactors SystemsPage to use the getEntities function and other new inventory features.
Please test it carefully, as there are many use-cases of the table and there are not so many tests.
This PR has to be merged only in ENVs where the InventoryTable is a version of (and higher): https://github.com/RedHatInsights/frontend-components/pull/1126 https://github.com/RedHatInsights/insights-chrome/pull/1425
> Refactor SystemsPage to use getEntities

- src/App.js
- src/App.scss
- src/Components/PresentationalComponents/AdvisoryColumn/AdvisoryColumn.js
- src/Components/PresentationalComponents/BasePfComponents/BaseDropdown.js
- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.scss
- src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
- src/Components/PresentationalComponents/CVEDetailsPageDescription/SnippetWithHeaderAndPopover.js
- src/Components/PresentationalComponents/CVEDetailsPageDescription/__snapshots__/SnippetWithHeaderAndPopover.test.js.snap
- src/Components/PresentationalComponents/CVEDetailsPageSidebar/CVEDetailsPageSidebar.js
- src/Components/PresentationalComponents/CVEDetailsPageSidebar/__snapshots__/CVEDetailsPageSidebar.test.js.snap
- src/Components/PresentationalComponents/CVEDetailsPageSummary/__snapshots__/CVEDetailsPageSummary.test.js.snap
- src/Components/PresentationalComponents/CvssVector/CvssVector.js
- src/Components/PresentationalComponents/Filters/CustomFilters/CvssCustomFilter.js
- src/Components/PresentationalComponents/Header/Breadcrumb.js
- src/Components/PresentationalComponents/Snippets/Label.js
- src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
- src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap
- src/Components/SmartComponents/InsightsSystemRule/InsightsSystemRule.js
- src/Components/SmartComponents/InsightsSystemRule/__snapshots__/InsightsSystemRule.test.js.snap
- src/Components/SmartComponents/Modals/CveStatusModal.js
- src/Components/SmartComponents/Modals/__snapshots__/ReportConfigModal.test.js.snap
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap
- src/Helpers/VulnerabilityHelper.js
- src/Helpers/__snapshots__/VulnerabilityHelper.test.js.snap
- src/Helpers/constants.js
- src/Helpers/severityLabels.scss
Resolves [VULN-1682](https://issues.redhat.com/browse/VULN-1682).
- remove inline styles where it made sense
- removed implicit `valign: -0.125em` on icons
Aside from cleanup this also might also help QA by providing class names and ids for more elements.
> VULN-1682 chore: Stylesheets cleanup

- src/Store/Reducers/CVEsStore.js
Fixes [VULN-1661](https://issues.redhat.com/browse/VULN-1661).
According to [patternfly example](https://www.patternfly.org/v4/components/table/react-demos/expandcollapse-all/):
1. expand all then collapse one should yield to `v`
2. expand all then collapse one by one every row should yield to `>`
3. expand one by one every row should yield to `v`
---
1. was ok in systems exposed page, but was not present in CVE page, which is fixed in this PR
2. and 3. is in PF example, but this cannot be solved simply when using pagination, because we can only track expandedness of CVE if it's on the current page; CVEs on other pages are not loaded
> VULN-1661 fix: Consistent expand all

- src/App.scss
- src/Components/PresentationalComponents/Filters/CustomFilters/CvssCustomFilter.js
- src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/CvssBaseScoreFilter.js
- src/Components/SmartComponents/Modals/__snapshots__/ReportConfigModal.test.js.snap
Had to move the external style to inline, because modal is mounted outside vuln app viewport and since chrome 2 update you cannot style outside of app viewport.
> fix: Fix CVSS filter misalignment in report modal

- src/Components/PresentationalComponents/CVEDetailsPageDescription/SnippetWithHeaderAndPopover.js
- src/Components/PresentationalComponents/CVEDetailsPageDescription/__snapshots__/SnippetWithHeaderAndPopover.test.js.snap
- src/Components/PresentationalComponents/CVEDetailsPageSidebar/__snapshots__/CVEDetailsPageSidebar.test.js.snap
- src/Components/PresentationalComponents/CVEDetailsPageSummary/__snapshots__/CVEDetailsPageSummary.test.js.snap
- src/Components/SmartComponents/Modals/BaseModal.js
- src/Components/SmartComponents/Modals/BusinessRiskModal.js
1. Delete `aria-label="Business risk popover"` from popover because it is used for both status and BR, it still has `id="popover"` so it is still targetable by QA.
2. Make both popovers go bottom, one of them would go right (obstruction the other one); now they both go bottom, so they don't obstruct themselves and the direction is consistent.
3. Add minimum height to modal's textareas (they are vertically resizable), so at least one line can fit
> fix: Minor modal and popover tweaks

- config/dev.webpack.config.js
Until the platform will switch to `console.redhat.com` with the flag `useCloud` we can still use the old paths from `cloud.redhat.com`
> chore: Use cloud.redhat.com paths

- package-lock.json
- package.json
pre-prod is being down almost a day now but with the new configuration (console.redhat.com) we cannot run prod.foo locally.  Thus I had to downgrade the configuration package.  In order to run prod.foo locally you need to run
1. `npm run start`
2.   `SPANDX_CONFIG=/home/HOME...`
** `npm run start:proxy` is not working
> chore: Downgrade config in order to work with prod.foo

- package-lock.json
- src/Components/SmartComponents/CVEs/CVEs.js
- src/Components/SmartComponents/CVEs/CVEs.test.js
- src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
- src/Components/SmartComponents/CVEs/CVEsTableToolbar.test.js
- src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
- src/Components/SmartComponents/CVEs/__snapshots__/CVEsTableToolbar.test.js.snap
- src/Store/Reducers/CVEsStore.js
- src/Store/Reducers/CVEsStore.test.js
Here is my proposal for the [bug 1793](https://issues.redhat.com/browse/VULN-1793). I applied the changes only to landing page, if we agree on the solution it should be applied to all pages.
Few words about the  implementation: 
1. I store in redux the previously loaded rows + the current loaded rows in the variable `prevLoadedRows`
2. with that I can retrieve the data of previously visited loaded rows
3. use `unionBy` functionality to avoid the duplicates in case you go back and forth (pages) it will store it only once
Drawback? 
- Storing potential big set of data in redux if the use decides to visit all pages 
known issues:
- We still have the issue with the Select all functionality, this PR doesn't fix this problem
> VULN-1793 fix(CVEsstore): Store previously loaded rows

- src/AppEntry.js
Now that chrome 2 is present in all envs, we can remove chrome 1 compatibility code, which fixed the problems with sticky headers while both versions of chrome were present in different envs.
> chore: Remove obsolete chrome 1 compatibility code

- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
Fixes [VULN-1843](https://issues.redhat.com/browse/VULN-1843).
Correctly dispatch `fetchAffectedSystemsByCVE` to update status in table and add `fetchCveDetails` to refresh status breakdown table in CVE detail header.
> fix: Refresh systems exposed page on status edit

- package-lock.json
- package.json
- src/App.scss
- src/Components/PresentationalComponents/EmptyStates/__snapshots__/EmptyState.test.js.snap
- src/Components/PresentationalComponents/ErrorHandler/__snapshots__/ErrorHandler.test.js.snap
- src/Components/PresentationalComponents/StaticPages/__snapshots__/NoAccessPage.test.js.snap
- src/Components/PresentationalComponents/StaticPages/__snapshots__/UpgradePage.test.js.snap
- src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
- src/Components/SmartComponents/CVEs/__snapshots__/CVEsTableToolbar.test.js.snap
- src/Components/SmartComponents/Modals/__snapshots__/ReportConfigModal.test.js.snap
- src/Components/SmartComponents/Reports/__snapshots__/ReportsPage.test.js.snap
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTableToolbar.test.js.snap
- src/Components/SmartComponents/SystemDetailsPage/__snapshots__/SystemDetails.test.js.snap
- src/Components/SmartComponents/SystemsPage/__snapshots__/SystemTableToolbar.test.js.snap
Fixes [VULN-1814](https://issues.redhat.com/browse/VULN-1814).
This bug affected all tables. Updated `@patternfly/react-core` to resolve [this issue](https://github.com/patternfly/patternfly-react/issues/5962). This fixed the problem only on landing page, so I had to add a new sass rule, which should not break anything as it is very specific and includes `.pf-m-hidden` so it should had `display: none` either way,
> VULN-1814 fix(toolbars): Remove unwanted bottom margin

- src/Components/PresentationalComponents/Header/Header.js
- src/Components/PresentationalComponents/StaticPages/__snapshots__/NoAccessPage.test.js.snap
- src/Components/PresentationalComponents/StaticPages/__snapshots__/UpgradePage.test.js.snap
- src/Components/SmartComponents/Reports/__snapshots__/ReportsPage.test.js.snap
This change doesn't change anything for wide enough resolutions, but fixes layout for narrow viewport devices, like portrait mobile.
> fix(CVE detail page): Improve responsiveness

- src/Components/PresentationalComponents/CVEDetailsPageDescription/CVEDetailsPageDescription.js
- src/Components/PresentationalComponents/CVEDetailsPageDescription/__snapshots__/CVEDetailsPageDescription.test.js.snap
- src/Components/PresentationalComponents/CVEDetailsPageSidebar/CVEDetailsPageSidebar.js
- src/Components/PresentationalComponents/CVEDetailsPageSidebar/__snapshots__/CVEDetailsPageSidebar.test.js.snap
- src/Components/PresentationalComponents/CVEDetailsPageSummary/CVEDetailsPageSummary.js
- src/Components/PresentationalComponents/CVEDetailsPageSummary/__snapshots__/CVEDetailsPageSummary.test.js.snap
- src/Components/PresentationalComponents/CvssVector/CvssVector.js
- src/Components/PresentationalComponents/CvssVector/__snapshots__/CvssVector.test.js.snap
- src/Components/PresentationalComponents/WithLoader/WithLoader.js
- src/Components/PresentationalComponents/WithLoader/WithLoader.test.js
- src/Components/PresentationalComponents/WithLoader/__snapshots__/WithLoader.test.js.snap
- completely refactor `WithLoader` component to remove very old and obsolete code and make it more useful in the future, new types of loaders available:
- **spinner**
- **table** - table of columns * rows skeletons
- **compactTable** - compact table of columns * rows skeletons
- **rectangle** -  multiple rows
- **inlineSkeleton** - one row, inline
- **skeleton** - one row, block level (default)
- improve skeletons for CVE detail page header
- add skeleton table for CVSS score breakdown
- description text align justified
1. Go to `CVEDetailsPage.js`
2. Locate line `<CVEPageContext.Provider value={cveDetails && { isLoading: cveDetails.isLoading }}>`
3. Replace `cveDetails.isLoading` with `true` to keep the loading and showing skeletons forever
> fix(CVE detail page): Update skeleton loading

- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCves.test.js.snap
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTableToolbar.test.js.snap
- src/Helpers/VulnerabilityHelper.js
- src/Helpers/__snapshots__/VulnerabilityHelper.test.js.snap
> VULN-672 fix: Add tooltip text to 'Unknown' severity label

- src/Store/Reducers/CVEsStore.js
- src/Store/Reducers/InventoryEntitiesReducer.js
From [unionBy documentation](https://lodash.com/docs/4.17.15#unionBy):
> Result values are chosen from the first array in which the value occurs.
So if an item is contained in both previously loaded rows and new data, we should prioritize the new attributes; otherwise we'd use the old attributes for overlapping items.
> VULN-1903 fix: Correctly refresh previously loaded rows

- src/Components/SmartComponents/Modals/CveStatusModal.js
Previously we sent `setCveStatus` waited for it to resolve and then we sent `setSystemCveStatus` and then we showed the success notification, so we waited for 2 requests to resolve. But if we supply `status_id` and `status_text` to `setSystemCveStatus` we can send these two requests simultaneously and we only need to wait for half the time.
> VULN-1925 fix: Make status change twice as fast

- .eslintignore
- package.json
- scripts/unused.mjs
We often update appearance of our app which means some translation keys get removed from the code, but still remain in the `messages.js` file. This script searches whole 'src/' directory to find keys which are unused. Script is ran using `npm run translations:unused` and is run when using `npm run translations`. It uses `eval()` but this script is dev only, so this shouldn't pose any danger.
> chore: Add script to detect unused translation keys

- .eslintrc.yml
- src/Components/PresentationalComponents/AdvisoryColumn/AdvisoryColumn.js
- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
- src/Components/PresentationalComponents/CVEDetailsPageSidebar/__snapshots__/CVEDetailsPageSidebar.test.js.snap
- src/Components/PresentationalComponents/CVEDetailsPageSummary/__snapshots__/CVEDetailsPageSummary.test.js.snap
- src/Components/PresentationalComponents/CvssVector/CvssVector.js
- src/Components/PresentationalComponents/CvssVector/__snapshots__/CvssVector.test.js.snap
- src/Components/PresentationalComponents/InsightsSystemRule/InsightsSystemRule.js
- src/Components/SmartComponents/CVEDetailsPage/CVEDetailsPage.js
- src/Components/SmartComponents/CVEs/CVEsTable.js
- src/Components/SmartComponents/Modals/BaseModal.js
- src/Components/SmartComponents/Modals/CveStatusModal.js
- src/Components/SmartComponents/Reports/Common/__snapshots__/firstPagePDF.test.js.snap
- src/Components/SmartComponents/Reports/Common/__snapshots__/tablePage.test.js.snap
- src/Components/SmartComponents/Reports/Common/tablePage.js
- src/Components/SmartComponents/SystemCves/SystemCveTable.js
- src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Components/SmartComponents/SystemsPage/SystemsPage.js
- src/Helpers/Hooks.js
Added `react/jsx-no-useless-fragment: 2` rule, which shows error when you are wrapping only 1 child in `React.Fragment`, which makes components returns a bit cleaner.
Also removed `Indent > MemberExpression: 0` (this makes this rule by default 1), so now when chaining functions on more lines they have to be indented.
```
something(...)
.then(...)
.catch(...)
```
```
something(...)
.then(...)
.catch(...)
```
> chore: Add jsx-no-useless-fragment lint rule

- src/Components/SmartComponents/Reports/ReportsPage.js
Previously if you exported PDF, received notification and then navigated to other page the notification would still be there.
> fix(Reports page): Clear notifs on unmount

- src/Components/SmartComponents/Reports/DownloadCVEsReport.js
- src/Components/SmartComponents/Reports/DownloadExecutive.js
- src/Components/SmartComponents/Reports/DownloadSystemsReport.js
- src/Components/SmartComponents/Reports/ReportsPage.test.js
Since PDF download button is now an async element, there is an additional delay to loading it. Before when user clicked there might have been a few seconds before `Exporting PDF` toast notification was displayed.
1. I fixed this delay, now toast alert is displayed immediately upon clicking the button
2. Fixed `Download executive report` button not changing text to `Loading...` when clicked
3. Removed these ugly spinners when report is being built (set `fallback` to `null`)
> fix: Make downloading PDF reports more responsive

- src/App.scss
- src/Components/PresentationalComponents/AdvisoryColumn/AdvisoryColumn.js
- src/Helpers/constants.js
Fix Firefox misalignment (VULN-1842), fix columns not being layed out uniformly (VULN-2021), put each advisory on separate line.
> VULN-1842 VULN-2021 fix: Fix table alignment

- src/Components/SmartComponents/CVEs/CVEs.js
- src/Components/SmartComponents/SystemCves/SystemCves.js
- src/Helpers/MiscHelper.js
- src/Helpers/MiscHelper.test.js
> VULN-2030 fix(CVEs pages): Retain sorting and filtering after status/BR change

- babel.config.js
- package-lock.json
- package.json
- src/Components/SmartComponents/Remediation/Remediation.js
This PR should not change any functionality, it will just make Remediation button mirror the version of Remediations from current environment as opposed to version of the imported package.
> VULN-2165 chore: Use federated modules for Remediation button

- src/Components/SmartComponents/CVEs/CVEsTable.js
- src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
- src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap
- src/Components/SmartComponents/SystemCves/SystemCveTable.js
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap
New version of patternfly table introduced `canCollapseAll` which adds expand all in table header which is true by default. But we already use expand all in table toolbar. This fix applies to CVE list table /cves and System CVEs table /systems/{system_id}.
> fix: Remove duplicate expand all button

- src/Components/SmartComponents/SystemCves/SystemCveTable.js
Description and screen capture of this bug is in last comment in https://issues.redhat.com/browse/VULN-2047
This bug was about sorting header not matching table header when checkboxes were not present, sorting header has to contain all columns including expand button column and checkbox column.
> fix(System CVE table): Fix sorting when canSelect is false

- package-lock.json
- package.json
This is in response to CVEs regarding node-forge, which is now 1.3.1
> chore(deps): bump frontend-components-config to 4.6.8

- src/Components/SmartComponents/Dashbar/Dashbar.js
- src/Helpers/MiscHelper.js
Interpret text inside announcement as HTML, allowing us to format the content - for example adding links or bold text.
To test:
1. Check whether Announcement message is correctly parsing HTML data
> Allow HTML formatting inside Dashbar

- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTableToolbar.js
- src/Components/SmartComponents/SystemsPage/SystemTableToolbar.test.js
- src/Components/SmartComponents/SystemsPage/SystemsPage.js
- src/Components/SmartComponents/SystemsPage/SystemsTableToolbar.js
- src/Components/SmartComponents/SystemsPage/__snapshots__/SystemTableToolbar.test.js.snap
- src/Helpers/Hooks.js
- src/Store/Actions/Actions.js
- src/Store/Reducers/InventoryEntitiesReducer.js
- src/Store/Reducers/reducersHelper.js
Removing `selectedRowsRawData` and `prevLoadedRows` state fields. Also making sure that `selectedRows` is array. It was sometimes an object...
Adds 2 TODOs comments as we need an update for 2 endpoints. We don't need the whole objects, just some attributes.
> VULN-1581 part2: Fixing 'select all' in Systems tables

- package-lock.json
- package.json
Update FEC config to version over 4.6.9 to prevent future problems when ESI tags are disabled on Akamai.
> chore: Update FEC config

- src/Components/SmartComponents/SystemsPage/__snapshots__/SystemTableToolbar.test.js.snap
- src/Helpers/constants.js
Add new options to OS filter
- RHEL 8.6
- RHEL 9.0
> fix: Add newest RHEL versions to OS filter

- src/Components/SmartComponents/Reports/DownloadExecutive.js
Moved `Loading...` text, which is shown after user clicks `Download report`, outside of `<a>` element so now user cannot initiate another download until the first download finishes.
> fix: Disable Exec report download button when already downloading

- locales/en.json
- package-lock.json
- package.json
- src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/OsVersionFilter.js
- src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/__mocks__/OsVersionFilter.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTableToolbar.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTableToolbar.test.js
- src/Components/SmartComponents/SystemsExposedTable/__snapshots__/SystemsExposedTableToolbar.test.js.snap
- src/Components/SmartComponents/SystemsPage/SystemTableToolbar.test.js
- src/Components/SmartComponents/SystemsPage/SystemsPage.js
- src/Components/SmartComponents/SystemsPage/SystemsTableToolbar.js
- src/Components/SmartComponents/SystemsPage/__snapshots__/SystemTableToolbar.test.js.snap
- src/Helpers/TableToolbarHelper.js
- src/Helpers/fixtures.js
- src/Messages.js
Implements https://issues.redhat.com/browse/VULN-2391.
1. Navigate to https://stage.foo.redhat.com:1337/beta/insights/vulnerability/systems.
2. Verify GET  /system_profile/operating_system is made.
3. Check whether OS filter matches the API response.
4. Check basic filter functions (chips loaded, values selected, table updated, URL search params updated, filters can be removed).
5. Navigate to any of CVEs page.
6. Do the same steps as for the systems list page.
> VULN-2391: OS filter displays only relevant values obtained from API (1/2)

- locales/en.json
- src/Components/SmartComponents/Reports/DownloadExecutive.js
- src/Messages.js
Update red exec report title from Vulnerabilities to Vulnerability as per https://docs.google.com/document/d/1IQ5BdyZApCYd_oz-RGIILJumrvI9RYMOWmaVA5bbloA page 6.
> fix: Update executive report title

- package-lock.json
- package.json
This is the latest version compatible with FEC/PDF generator
> chore: Update react-charts to fix CVE

- package-lock.json
- package.json
Fixes https://issues.redhat.com/browse/VULN-2434.
CVE is fixed in version 2.0.3 https://github.com/webpack/loader-utils/issues/212
> chore: Pin loader-utils package version to fix a CVE

- src/Helpers/CVEHelper.js
- src/Helpers/constants.js
Resolves [VULN-2468](https://issues.redhat.com/browse/VULN-2468).
Vulnerability CVE detail page (AKA systems exposed page) for CVEs with security rule distinguishes three kinds of systems. If a CVE has a rule it does mean that all affected systems by that CVE are hit by a rule.
1. vulnerable and not hit
2. vulnerable and hit by a rule -- backend sends `rule.rule.reason` from endpoint
3. affected but not vulnerable -- has a green badge saying "Not vulnerable" -- system is not affected to the CVE because there is some mitigation in place (for example system is affected by Bluetooth CVE, but is not vulnerable, because it has disabled Bluetooth module) -- backend always send `mitigation_reason` from endpoint, that's how they are recognized by the frontend.
Previously affected but not …
> fix: Systems with partial rule hit can also be affected but not vulnerable

- src/Components/SmartComponents/SystemCves/SystemCves.js
- src/Helpers/VulnerabilityHelper.js
- src/Store/Reducers/SystemCvesStore.js
Vulnerability store reducers are implemented inconsistently, for example this one was using `applyReducerHash` which is a vastly different approach to other stores, which use switch statements.
I removed `applyReducerHash` and moved contents of individual functions into case blocks of switch statements. Also did some small cleanups for readability. But if you compare previous actions' code to current it should functionally be the same.
There should be no change in functionality. Go to System CVEs (System detail) page and try to perform various table operations and see if everything works as it should.
> chore: Refactor SystemCvesStore

- src/Components/SmartComponents/CVEDetailsPage/__snapshots__/CveDetailsPage.test.js.snap
- src/Components/SmartComponents/CVEs/CVEs.js
- src/Components/SmartComponents/CVEs/CVEs.test.js
- src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
- src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
- src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
- src/Components/SmartComponents/SystemCves/SystemCves.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTableToolbar.js
- src/Components/SmartComponents/SystemsPage/SystemsPage.js
- src/Components/SmartComponents/SystemsPage/SystemsTableToolbar.js
- src/Helpers/Hooks.js
Resolves [VULN-1406](https://issues.redhat.com/browse/VULN-1406).
There should be no change in functionality. Isolated all column mgmt functionality into a hook. This will make it much easier to:
1. edit column mgmt functionality in all pages at once
2. add column mgmt to a new table if we ever create one
3. port column mgmt to another app
Try to change columns from column management modal in all four tables.
> chore: Refactor column management to use hooks

- src/Components/SmartComponents/SystemDetailsPage/SystemDetails.js
- src/Components/SmartComponents/SystemDetailsPage/SystemDetailsPage.js
- src/Store/Reducers/SystemDetailsPageStore.js
- src/Store/Reducers/SystemDetailsPageStore.test.js
Resolves: [RHIF-170](https://issues.redhat.com/browse/RHIF-170)
This PR removes AppInfo federated module usage together with rendering `SystemDetail` component using activeApps in redux. Thus, making the application's complexity and performance. 
How to test:
Basic functionality should not change. Observer that the system details page works as expected.
> perf(RHIF-170): remove AppInfo usage together with activeApps in redux

- .eslintrc.yml
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
Fixes [VULN-2525](https://issues.redhat.com/browse/VULN-2525).
> When a cve details page is selected example(https://console.stage.redhat.com/beta/insights/vulnerability/cves/CVE-2023-22809?page=1&page_size=20&show_advisories=true&sort=-updated) the default filter of sort=-updated is applied. 
> If a user attempts to go back to the CVE list page this filter is also applied (https://console.stage.redhat.com/beta/insights/vulnerability/cves?affecting=true&page=1&page_size=20&show_advisories=true&sort=-updated) which causes an error
1. Go to CVE list page (landing page)
2. Click on any CVE
3. Go back to the previous page using browser history
4. CVE list page should be displayed correctly
5. Repeat this multiple times as this bug did not happen everytime
`setUrlParams` function was in the …
> fix: Fix crash when navigating back from CVE detail to CVE list page

- src/Store/Reducers/reducersHelper.js
Bug 1: Previously applying the AAP or MSSQL workload in global filter might not trigger a rerefresh of table data.
Bug 2: Previously resetting global filter configuration with "Clear filters" button might not clear AAP nor MSSQL workload.
Both bugs have been fixed.
Verify that selecting, deselecting and resetting workloads in global filter has the correct effect on the table.
> fix: Fix global filter not applying and resetting correctly

- src/Components/SmartComponents/SystemCves/SystemCveTable.js
- src/Components/SmartComponents/SystemCves/SystemCves.test.js
- src/Components/SmartComponents/SystemCves/SystemCvesTable.test.js
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTableToolbar.test.js.snap
- src/Helpers/APIHelper.js
- src/Helpers/CVEHelper.js
- src/Helpers/CVEHelper.test.js
- src/Helpers/VulnerabilityHelper.js
- src/Helpers/VulnerabilityHelper.test.js
- src/Helpers/__snapshots__/VulnerabilityHelper.test.js.snap
- src/Store/Reducers/CVEDetailsPageStore.js
- src/Store/Reducers/InventoryEntitiesReducer.js
- src/Store/Reducers/SystemCvesStore.js
- src/Store/Reducers/SystemCvesStore.test.js
[VULN-2534](https://issues.redhat.com/browse/VULN-2534)
patch_access is a parameter previously used to indicate whether user had permission to access Patchman advisory information, but advisories information is not available from vulnerability engine therefore user does not need Patchman access to receive the information, so the parameter is currently always returned as true and is redundant.
show_advisories is a similar parameter that has been made obsolete by storing advisory information in Vuln engine. Also this parameter is ignored by the backend either way.
> refactor: Remove patch_access and show_advisories parameters

- src/Components/SmartComponents/Remediation/Remediation.js
- src/Helpers/Hooks.js
In stage, go to Inventory -> Systems and choose a system that has CVEs with multiple resolutions (If logged into qa account, try the following system: rhiqe.fca4cbab-d008-4fbf-ba39-391754625f22.iqe-insights-client-plugin). Next, select the Vulnerability tab.
From there, I like to add filters to include systems with "Has security rule" and "Has a known exploit". This usually gives you a few CVEs that will get you multiple resolutions.
Now, try selecting multiple CVEs one-by-one and click the Remediate button. Now, check the "Network" tab in developer tools and check for the resolutions call. You should notice in the "Payload" tab that the issues are structured like so: `"vulnerabilities:CVE-2022-0847:CVE_2022_0847_kernel|CVE_2022_0847_KERNEL"`
If you now redo the actions above, but select …
> fix(REMEDY-300): correctly fetch resolutions

- package-lock.json
- package.json
- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
- src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
Ticket: https://issues.redhat.com/browse/VULN-2419
1. open CVE detail page of a CVE with Security rule
2. click the "Filter by X systems" link inside any security rule breakdown box
3. your page should automatically scroll down to the table
> feat: Add anchor links to Security rule summary links

- package-lock.json
- package.json
- src/Components/SmartComponents/SystemsPage/SystemsPage.js
- src/Helpers/constants.js
- src/Utilities/useFeatureFlag.js
https://issues.redhat.com/browse/ESSNTL-3717
How to test - check that the groups filter is present as well as groups filter, check that the groups column is present in the column manager.
Try to turn on/off the feature flag and check that the table hides all info about groups.
The sorting by group is not implemented
Data about groups is not available until it implemented so group links are not present in the column
Groups feature flag ON
Groups feature flag OFF
> feat(ESSNTL-3717): Add Inventory groups filter and column

- src/Components/SmartComponents/Modals/CvePairStatusModal.js
- src/Components/SmartComponents/SystemCves/SystemCves.js
- src/Components/SmartComponents/SystemCves/SystemCves.test.js
https://issues.redhat.com/browse/VULN-2637
During some refactoring of selected items, the names of some parameters got changed which caused multiple issues while editing the status on the CVE detail page:
1. If you try to edit status, don't open the status select and click "Save", you'd get an error
2. If you selected an item which already has status/justification set, the form field did not get prefilled.
> Fix System-CVE pair status not being set correctly

- locales/en.json
- src/Components/SmartComponents/CVEs/CVEsTable.js
- src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
- src/Messages.js
Part of https://issues.redhat.com/browse/VULN-2672
There is a feature flag which controls the enablement of CVEs without errata feature, the feature flag is stored on backend and is sent in meta section of most API responses. It has three values:
- globally disabled – don't show option to show/hide CVEs without Advisories, backend retuns null
- account disabled – show option to show CVEs without Advisories, backend returns false
- account enabled – show option to hide CVEs without Advisories, backend returns true
This PR makes it so that if backend sends null, then we want to act as if the feature is account disabled (for example hide Advisory filters) and don't show the button to toggle the feature in CVEs list table toolbar.
> Implement global feature flag for CVEs without errata

- src/Components/PresentationalComponents/TableColumns/RemediationColumn.js
- src/Components/SmartComponents/CVEs/CVEsTable.js
- src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
- src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
- src/Components/SmartComponents/CVEs/__snapshots__/CVEsTable.test.js.snap
- src/Components/SmartComponents/CVEs/__snapshots__/CVEsTableToolbar.test.js.snap
- src/Components/SmartComponents/SystemCves/SystemCveTable.js
- src/Components/SmartComponents/SystemCves/SystemCvesTable.test.js
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Components/SmartComponents/SystemsPage/SystemsPage.js
- src/Helpers/constants.js
- src/Store/Reducers/CVEDetailsPageStore.js
- src/Store/Reducers/InventoryEntitiesReducer.js
- src/Store/Reducers/SystemCvesStore.js
- src/Store/Reducers/SystemsPageStore.js
Includes partial fix to https://issues.redhat.com/browse/VULN-2768
- Fix Remediation column being on two lines in CVE detail table in mobile view
- Fix Advisory column being titled "column-9" in mobile view
- [Refactor] Use DEFAULT_PAGE_SIZE instead of hardcoded 20 in tables
- Improved CVE list and System CVE list tables loading skeletons:
- Number of rows reflects loaded table
- Table header reflects loaded table
- Current sort reflects loaded table
- Selecting checkboxes reflect loaded table
- Mobile view shows header titles instead of "column-n"
> Improve table mobile views and skeletons

- src/Helpers/constants.js
[ESSNTL-5048](https://issues.redhat.com/browse/ESSNTL-5048)
Added `appName` to allowed query params so the Vulnerability Tab in Inventory Detail can work properly
[Related Inventory PR](https://github.com/RedHatInsights/insights-inventory-frontend/pull/1992)
> fix(ESSNTL-5048): Add param for Inventory

- src/Components/PresentationalComponents/Filters/CustomFilters/CheckboxCustomFilter.js
- src/Components/SmartComponents/Modals/ReportConfigModal.js
Fixed the following bug:
1. Make sure CVEs without advisories are shown (use the button in CVE list page toolbar kebab)
2. Go to Reports page
3. The page crashes after a moment
> Fix Reports page crash when CVEs without errata FF was off

- locales/en.json
- src/Components/PresentationalComponents/AdvisoryColumn/AdvisoryColumn.js
- src/Components/PresentationalComponents/TableColumns/RemediationColumn.js
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTable.test.js.snap
- src/Components/SmartComponents/SystemCves/__snapshots__/SystemCvesTableToolbar.test.js.snap
- src/Helpers/VulnerabilityHelper.js
- src/Helpers/__snapshots__/VulnerabilityHelper.test.js.snap
- src/Helpers/constants.js
- src/Messages.js
https://issues.redhat.com/browse/VULN-2677
https://issues.redhat.com/browse/VULN-2673
https://issues.redhat.com/browse/VULN-2578
1. Find CVE that has Advisory not available
2. Go to column management and enable Remediation column
3. Make sure tooltips on question mark icons in columns are as in mockups (except the link text, that should not say Documentation)
> Update Advisory column tooltip on detail pages

- package-lock.json
- package.json
- src/Helpers/APIHelper.js
- src/Helpers/Hooks.js
- src/Helpers/constants.js
Implements https://issues.redhat.com/browse/ESSNTL-3717.
This integrates the group filter and column with the /systems page. The column Group shows a group of each system: if it is not a member of any group, then 'N/A' is rendered, otherwise the name of the group. Also, users now can filter by group(s).
Verify basic filtering by the groups, and make sure the group names are mapped correctly to each host.
> feat(ESSNTL-3717): Integrate groups with /systems

- src/Components/SmartComponents/CVEDetailsPage/CveDetailsPage.test.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.test.js
- src/Helpers/APIHelper.js
- src/Helpers/constants.js
Implements https://issues.redhat.com/browse/ESSNTL-3948.
Add the group filter and column to the CVE affected systems page (/cve/%id).
Check that the table shows groups for each host, and you are able to filter by groups.
https://github.com/RedHatInsights/vulnerability-ui/assets/31385370/1b6b41ce-bab4-4eac-b69f-0441d8d7af7a
> feat(ESSNTL-3948): Group filter on exposed table

- src/Helpers/constants.js
This helps to avoid the run-time error while build the table with security rules.
Find a CVE with a security rule, and check that you are able to open the CVE's details page normally, and the systems table should be loaded without issues.
> fix(ESSNTL-3948): Wrap the group column value in span

- src/index.js
This removes the now obsolete `Router` component, since the router context is now provided by the chrome router.
> fix(SystemsCVES): RHINENG-1872 - Remove obsolete Router

- src/Helpers/TableToolbarHelper.js
- src/Helpers/TableToolbarHelper.test.js
- src/Store/Reducers/SystemsPageStore.js
This fixes resetting the filters to the default filters on the Systems page.
1) Go to Vulnerability app, Systems page
2) Remove default "Systems with Vulnerability analysis enabled: Enabled systems" filter
3) Click "Reset filters"
4) The default filter should be enabled again
> fix(SystemsTable): Fix resetting to default filters

- src/Components/SmartComponents/Reports/Common/__snapshots__/firstPagePDF.test.js.snap
- src/Components/SmartComponents/Reports/Common/__snapshots__/tablePage.test.js.snap
- src/Components/SmartComponents/Reports/Common/tablePage.js
Resolves: https://issues.redhat.com/browse/RHIF-303
The system name in CVE report on the Reports page should be converted into a link so that it takes the user to the corresponding CVE details page on the UI.
Acceptance criteria:
The system row is linkable to the CVE details
The link will go to the conventional tab if there are any conventional systems.
The link will go to the immutable tab if there are no conventional systems.
> feat(RHIF-303): convert system name in CVE report to a link

- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
- src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.test.js
- src/Components/PresentationalComponents/CSAwRuleBox/NotVulnerableBox.js
- src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
- src/Components/PresentationalComponents/CVEDetailsPageSummary/CVEDetailsPageSummary.js
- src/Components/SmartComponents/CVEDetailsPage/CVEDetailsPage.js
- src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/ImmutableDevices.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Store/Reducers/ImmutableDevicesStore.js
This PR enables the security rule filter and No vulnerable systems filter to be applied for both Conventional and immutable devices.
To test:
1. find a cve that has known exloits and also a security rule associated
2. Click on it and go to CVE detail page
3. Click on the filter for Security rule header card
4. observe that both tabs are filtered with it
5. Repeat the same thing with No vulnerable systems card
> feat(RHIF-294): apply cve detail header filters  apply to both conventional and immutable systems

- src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/ImmutableDevices.js
Passes onRowClick function to immutable device module to redirect the user when the system name is clicked in the Name column.
> chore(ImmutableDevice): pass onRowClick to ImmutableDevice module

- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Components/SmartComponents/SystemsPage/SystemsPage.js
- src/Helpers/Hooks.js
- src/Helpers/MiscHelper.js
- src/Helpers/constants.js
Associated Jira ticket: https://issues.redhat.com/browse/RHINENG-1838.
This makes the "Group" column sortable on two views: /vulnerability/systems and /vulnerability/cves/%id.
The Inventory change is not yet merged to ensure that the tenant apps support sorting first and avoid breaking change.
1. Pull this Inventory PR locally https://github.com/RedHatInsights/insights-inventory-frontend/pull/2070.
2. Run Vulnerability with this PR `npm run start -- --port=8004`
3. Run Inventory with `LOCAL_APPS=vulnerability:8004~http npm run start:proxy`
4. Navigate to the updated views (in stage-stable environment) and make sure you can sort by system groups.
5. Check the URL search parameters too: while sorting the table, and then refreshing the page - the same sorting must be applied.
> feat(RHINENG-1838): Make group column sortable

- src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/ImmutableDevices.js
- src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/helpers.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Components/SmartComponents/SystemsPage/SystemsPage.js
- src/Helpers/Hooks.js
- src/Helpers/TableToolbarHelper.js
This fixes existing bugs related to the recent OS refactor. Issues are, when an OS filter is applied, it does not get reflected in the URL. Also, the 'Reset filter' does not get shown next to the OS filter. 
Marking blocker as this blocks QA verification of edge part work.
> fix(RHINENG-3366): apply OS filter into URL, show reset filters button

- src/App.js
- src/Utilities/VulnerabilityRoutes.js
- src/Utilities/VulnerabilityRoutes.test.js
This PR is intended to show a loading state while a zero state is being checked. This solves the issues that happen when API calls are in progress and zero state is shown by default for a milli-second. This will improve the UX and slick page transition. There should no be any change to zero state itself.
The PR also adds test coverage to zero-state logic.
To test:
1. Make sure that the zero state is not shown in the following cases:
-   edge is enabled and there are both conventional and edge systems
- edge is enabled and there is at least one type of system
- edge is disabled, if there is a conventional system, regardless of edge system
> chore(VulnerabilityRoutes): introduce loading state

- package-lock.json
- package.json
- src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/ImmutableDevices.js
- src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/helpers.js
- src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/helpers.test.js
- src/Helpers/Hooks.js
This fixes existing issues related to group column sorting in the immutable devices tab. Currently, if that column is sorted the UI breaks doe to API error.
To test:
1. Find a CVE with immutable devices
2. Open the details page
3. try sorting by group column
4. Observe that the UI does not brake and sorting works
> fix(RHINENG-1838): groups sorting is fixed in Immtable devices

- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Components/SmartComponents/SystemsPage/SystemsPage.js
Fixes https://issues.redhat.com/browse/RHINENG-2802.
This removes all occurrences of the inventory groups feature flag since the feature is considered stable.
> chore(RHINENG-2802): Remove inventory groups feature flag

- src/Helpers/constants.js
This changes the text for when a system has no group from 'N/A' to 'No group' in grey wording. 
https://issues.redhat.com/browse/RHINENG-3653
> fix(RHINENG-3653): Update Groups column default text

- src/Helpers/constants.js
Removes the extra icon on initial table load in inventory pages by removing sortable table transformer. The table columns are by default made sortable in inventory module and advisor should not another transformer that is causing the extra icon.
> fix(SystemsExposed): remove extra sort icons in the table

- src/Helpers/ReportsHelper.js
This fixes the reported bug in https://issues.redhat.com/browse/RHINENG-3072.
The advanced CVE report has different wording according to the systems affecting filter state. The issue was that when the pdf result was filtered by only edge or conventional systems, the system counts in the report sub-header showed the total count of both edge and conventional systems which is incorrect. This fixes it by showing the correct edge/conventional count when it is an edge-only report or conventional-only report.
To test:
1. Navigate to /reports page
2. Open advanced CVE report modal
3. Filter the pdf result by edge systems 
4. Generate the report
5. Observe that the edge system count in the report header matches the value in the `meta.system_count_per_type` object from …
> fix(RHINENG-3072): pass correct system count to report sub-header

- src/Helpers/ReportsHelper.js
Removes unnecessary dot inside CVE pdf report
1. Visit reports page
2. generate a report with both conventional immutable systems
3. observe that there is only one dot in the subheader: 'vulnerability service identified 2,606 CVEs within this criteria, impacting at least one of your analyzed 3 RHEL systems, consisting of 2 conventional and 1 immutable.'
> fix(RHINENG-3072): remove obsolete dot in cve pdf report

- src/Utilities/VulnerabilityRoutes.js
I have noticed that this Route element is the exact same as the 'cvesPage' one, so this PR removes the duplicate
They both get the same path string and present the same element 'LandingPage' so there is no need for both Routes
> chore(VulnerabilityRoutes): Remove duplicate Route element

- src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
- src/Components/SmartComponents/Reports/ReportsPage.js
- src/Helpers/APIHelper.js
- src/Helpers/MiscHelper.js
- src/Store/Actions/Actions.js
This PR addresses issue [#RHINENG-7963](https://issues.redhat.com/browse/RHINENG-7963)
When attempting to "select all" CVEs in the CVEs Page, none are selected
With this code selecting all CVEs works
The reason why this bug occurres:
If a user has Edge systems in their account, we need to convert the affecting param to be in affectingHostType 
So, we use hybrid system filter to determine this.
- If the user have both Conventional & Edge systems, we convert the affecting params to be in affectingHostType params because affecting is no longer being used in the backend in this case.
- If the user has only Conventional systems, the backend still uses affecting param, so there is no need for the conversion.
Because affecting param is no longer being used in the backend in the first case, …
> fix(RHINENG-7963): Bug with select all CVEs option on CVEs page

- src/Helpers/MiscHelper.js
[RHINENG-3205](https://issues.redhat.com/browse/RHINENG-3205)
Global filter is lost after reload because the hash is lost.
How to test:
1. Go to Systems page, apply some filters, apply a global filter and refresh
2. The data should be the same and the global filter chip should be visible
3. Repeat for CVE Details page
> fix(RHINENG-3205): Global filter kept after refresh

- src/Components/PresentationalComponents/Filters/CustomFilters/TagFilter.js
https://issues.redhat.com/browse/RHINENG-9580
> RHINENG-9580 Fix tag modal crashing

- locales/en.json
- src/Components/SmartComponents/SystemCves/SystemCves.js
- src/Messages.js
- src/Utilities/VulnerabilityRoutes.js
- src/index.html
Resolves: https://issues.redhat.com/browse/RHINENG-9387
Updates page titles according to 'Current concept' column, single line treatment in this [sheet](https://docs.google.com/spreadsheets/d/1Uhwn6i9B383xUbnRQ2IWY3EZ6dihc-UfkHxnR_c7zXI/edit#gid=1001620868)
> chore(RHINENG-9387): update page titles

- src/Components/SmartComponents/Modals/CvePairStatusModal.js
[RHINENG-10236](https://issues.redhat.com/browse/RHINENG-10236)
State was ordered in the wrong way
1. Go to systems and pick a system that has some CVEs
2. In the table click the kebab menu and click "Edit status"
3. There shouldn't be an error
> fix(RHINENG-10236): Edit status in System detail

- src/App.js
- src/App.scss
- src/Components/PresentationalComponents/Snippets/PageLoading.js
- src/Components/SmartComponents/CVEs/CVEs.js
- src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
- src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/ImmutableDevices.js
- src/Components/SmartComponents/Reports/ReportsPage.js
- src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
- src/Components/SmartComponents/SystemCves/SystemCves.js
- src/Components/SmartComponents/SystemDetailsPage/SystemDetails.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Components/SmartComponents/SystemsPage/SystemsPage.js
- src/Utilities/VulnerabilityRoutes.js
- src/Utilities/VulnerabilityRoutes.test.js
- src/index.js
Essentially, this is an effort to improve the perceived performance of CVEs page. Before this change, the whole table was triggered loading and once the request to fetch cves for the table resolves, according to the advisor_availability info in the metadata, a new filter 'Advisor availability filter' was added. This would result in complete re-render of the table and the same API request to be triggered once more. Now, the advisory availability info is fetched on the very first page load with limit:1 and provided across components using react context.
Furthermore, there is another improvement for the general page loading user experience. Before, for example, while CVEs page was loading, the spinner would be displayed first in the center, then on top smaller, then on top bigger. This was …
> Improve advisor availability filter and general page loading user experience

- src/Components/PresentationalComponents/StaticPages/NoAccessPage.js
- src/Components/PresentationalComponents/StaticPages/UpgradePage.js
- src/Components/SmartComponents/CVEDetailsPage/CVEDetailsPage.js
- src/Components/SmartComponents/Dashbar/Dashbar.js
- src/Components/SmartComponents/LandingPage/LandingPage.js
- src/Components/SmartComponents/Reports/ReportsPage.js
- src/Components/SmartComponents/SystemDetailsPage/SystemDetailsPage.js
- src/Components/SmartComponents/SystemsPage/SystemsPage.js
This should not change anything about the app, only that the console errors with deprecation warnings go away, not even snapshots were affected.
> chore: Remove deprecated Main component

- src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
- src/Utilities/VulnerabilityRoutes.js
This fixes https://issues.redhat.com/browse/RHINENG-10459 by routing to SytemsCVEs using InsightsElement. Before this, as the component was not wrapped with InsightsElement, account context, and also other insights element component logic (e.g zero-state check) were not enabled on it. Now, account state context properly passes the required info `includesCvesWithoutErrata` to SystemCVEs and thus the filter is fixed.
> fix(RHINENG-10459): route SystemDetails page using InsightsElement

- src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/ImmutableDevices.js
- src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/ImmutableDevices.test.js
- src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/helpers.js
- src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/helpers.test.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
- src/Components/SmartComponents/SystemsPage/SystemsPage.js
- src/Helpers/MiscHelper.js
- src/Helpers/constants.js
- src/Store/Reducers/CVEDetailsPageStore.js
- src/Store/Reducers/ImmutableDevicesStore.js
- src/Store/Reducers/SystemsPageStore.js
Renames groups to workspaces. I have created another PR to put the work behind flags and to be able to just ever when we need to remove the flag.
> fix(RHINENG-10415): reword groups to workspaces

- cypress/utils/table.js
- src/Components/PresentationalComponents/CVEDetailsPageDescription/CVEDetailsPageDescription.test.js
- src/Components/PresentationalComponents/CVEDetailsPageDescription/__snapshots__/CVEDetailsPageDescription.test.js.snap
- src/Components/PresentationalComponents/CVEDetailsPageSidebar/CVEDetailsPageSidebar.test.js
- src/Components/PresentationalComponents/CVEDetailsPageSidebar/__snapshots__/CVEDetailsPageSidebar.test.js.snap
- src/Components/PresentationalComponents/Kebab/KebabItems.js
- src/Components/PresentationalComponents/Kebab/__snapshots__/KebabItems.test.js.snap
- src/Components/SmartComponents/CVEs/CVEs.cy.js
- src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
Fix and reenable some skipped tests and remove usage of autogenerated OUIA ids.
> Improve tests after PF5 migration

- cypress/support/component.js
- package-lock.json
- package.json
- src/Components/SmartComponents/CVEs/CVEs.cy.js
- src/Components/SmartComponents/CVEs/CVEs.js
https://issues.redhat.com/browse/RHINENG-10340
- use cypress/react package compatible with React 18
- update cypress package to the latest version
- fix failing tests by
- using `cy.get('body').should('not.contain', 'Reset filter');` instead of `cy.contains('Reset filter').should('not.exist');` because the newer versions of cypress evaluate `cy.contains(<<text>>)` to `undefined`
- removing `specPath` from the URL params, which is injected by cypress and interfearing with filter loading from URL params during page initialization
> chore(Cypress): Fix Cypress config and failing tests

- src/Components/SmartComponents/SystemDetailsPage/SystemDetailsPage.js
There was an issue on sysdetails page where when navigating from inventory, and going to vulnerability systems details page, a large gap would appear in between the detail header and the table. 
This is a result of double inventory classes. Ive removed the class is this PR as its redundant, and gone in here, removed the class, and seperated the table from the header component. 
https://github.com/RedHatInsights/insights-inventory-frontend/pull/2235
> fix(sysdetails): Fixes css issue on sysDetails page

- locales/en.json
- src/Components/PresentationalComponents/Kebab/KebabItems.js
- src/Components/SmartComponents/Reports/DownloadCVEsReport.js
- src/Components/SmartComponents/Reports/DownloadSystemsReport.js
- src/Messages.js
Changes "Export as PDF" to "Export to PDF" as we need to be consistent across apps
> fix(RHINENG-13529): Make PDF export naming consistent

- src/Components/SmartComponents/Modals/BusinessRiskModal.js
- src/Components/SmartComponents/Modals/CveStatusModal.js
Submitting changes to the Edit Status and Edit Business Risk modals via the CVE details page causes an error notification. Changes from [RHINENG-11501](https://github.com/RedHatInsights/vulnerability-ui/pull/2148) caused the issue.
To repro:
- Go to CVEs page
- Select a CVE to go to its details page
- Click the "Actions" dropdown in the details header and select either edit option Apply change in modal
Upon submitting changes in the modal, you will get an error notification, but if you refresh, you'll notice the change was properly made.
> fix(RHINENG-13960): Edit status/biz risk modal error

- src/Components/PresentationalComponents/Filters/CustomFilters/SelectCustomFilter.js
This PR https://github.com/RedHatInsights/vulnerability-ui/pull/2161 implemented a new version of the Publish date filter in the Reports modal. But it introduced a bug. When you opened the Publish date dropdown and then clicked on another dropdown, the Publish date dropdown would stay open.
This PR makes sure the dropdown closes when you click out of it. It also wraps the component in a div with the proper class and styles to add padding.
> fix(RHINENG-12947) close dropdown on outside click

- src/Components/SmartComponents/Reports/ReportsPage.js
- src/Components/SmartComponents/Reports/ReportsPage.test.js
To reproduce:
1. Go to https://console.redhat.com/insights/vulnerability/cves
2. At top in 'Filter by tag' select a value with systems
3. Navigate to https://console.redhat.com/insights/vulnerability/reports#SIDs=&tags=
4. Select Create report
5. Error is displayed
The issue is that the `useSelector` on ReportsPage was not putting the tags into an array, AND if there were no tags, then it wasn't returning an empty array properly.
Make sure to apply multiple variations of workloads, SAP IDs, and tags to make sure this feature works correctly.
> fix(RHINENG-12310): Tag filter error on Reports page

- .github/workflows/sentry.yml
- .gitignore
- fec.config.js
- package-lock.json
- package.json
This onboards Vulnerability to sentry to receive proper error reporting/routing, as well as the automation workflow that sends debugIDs up on a merge to master + sourceMap automation when a release is made too prod
https://issues.redhat.com/browse/RHINENG-15389
> feat(RHINENG-1539): Onboard Vulnerability to Sentry Instance

- src/Components/PresentationalComponents/VersionLockIconTooltip/VersionLockIconTooltip.js
- src/Components/PresentationalComponents/VersionLockIconTooltip/VersionLockIconTooltip.test.js
- src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.test.js
- src/Components/SmartComponents/SystemsPage/SystemsPage.fixtures.js
- src/Components/SmartComponents/SystemsPage/SystemsPage.test.js
- src/Helpers/constants.js
- src/Store/Reducers/SystemsPageStore.js
This PR notifies a user if a system's OS version is locked. When version locking is enabled for a system i.e. a system's OS is tied to a release version, that can affect the count of applicable and installable errata\advisories.
The backend now passes a key from the `/systems` api endpoint called `rhsm_lock` and the value is the locked version number. With this PR, we check on the Systems table as well as the CVEs -> CVEDetails tables. When the `rhsm_lock` parameter has a value, we include an icon with a tooltip that tells the user "Your RHEL version is locked..." and at which version it is locked at.
> fix(RHINENG-12778): Add tooltip for locked OS versions

- src/Components/SmartComponents/Modals/ReportConfigModal.js
- src/Components/SmartComponents/Modals/ReportConfigModal.test.js
- src/Components/SmartComponents/Reports/DownloadExecutive.js
- src/Components/SmartComponents/Reports/ReportsCards.js
- src/Components/SmartComponents/Reports/ReportsPage.js
- src/Components/SmartComponents/Reports/ReportsPage.test.js
- src/Components/SmartComponents/Reports/__snapshots__/ReportsPage.test.js.snap
- src/Helpers/Hooks.js
- src/Helpers/constants.js
- src/Messages.js
This PR adds a new card to the Reports page. It is hiddent behind a feature flag, `vulnerability.exposure-by-os-minor.enabled`. To test, simply go to Vulnerability -> Reports and check for the existence of the OS report card when the flag is flipped on or off. The link on the card should not be functional.
This PR also refactors the rendering of the cards as well as removes a redundant useFeatureFlag hook. It also removes some intl usage.
> feat(RHINENG-16846): Add operating systems report card

- fec.config.js
- package.json
- src/Components/SmartComponents/Modals/OsExposureReportModal/LifecycleSelect.js
- src/Components/SmartComponents/Modals/OsExposureReportModal/OsExposureReportExportPdfButton.js
- src/Components/SmartComponents/Modals/OsExposureReportModal/OsExposureReportModal.js
- src/Components/SmartComponents/Reports/OsExposureReport.js
- src/Helpers/APIHelper.js
- src/Helpers/constants.js
To test this, run the commands in the comments below. You'll visit the Vulnerability -> Reports page and select the "Report by operating system versions" report to open the modal.
This PR does a couple of basic things.
1. It sets some loading states for the modal so that when the fetch for data happens on modal open, and when the export happens, buttons are disabled.
2. It connects this modal to the pdf-generator service so that we can export an empty report. The component for the pdf template should be receiving the data.
> feat(RHINENG-16848): Set up os exposure pdf-generator

- src/Components/SmartComponents/Modals/OsExposureReportModal/LifecycleSelect.js
- src/Components/SmartComponents/Modals/OsExposureReportModal/LifecycleSelect.test.js
- src/Components/SmartComponents/Modals/OsExposureReportModal/OsExposureReportModal.js
- src/Components/SmartComponents/Modals/OsExposureReportModal/osExposureReport.fixtures.js
- src/Helpers/constants.js
This PR updates the way we make OS version and lifecycle selections for the PDF. We want to use the `selectedOsVersions` array as a reference for the pdf to get only the data it needs. So if a user select RHEL 8.8, it will default to only the `minor` lifecycle data.
```
[
    {
        8.8: {
           minor:  { ...data }
        }
    }
]
```
And, if a user changes the lifecycle selection to Extended Support:
```
[
    {
        8.8: {
           eus: { ...data }
        }
    }
]
```
> feat(RHINENG-17936): update exposure selection
